<?php

/*
  Project: CSV Product Import
  Author : karapuz <support@ka-station.com>

  Version: 3 ($Revision: 93 $)

 */


function trim_value($element) {
    return trim($element);
}

class ControllerToolImportFix extends Controller {

    public function index() {
        $attribute_name = "Attributes";
        $str = 'Solid;Diamond-cut;14k Yellow gold;Lobster;Special lengths avail.;
Solid;Diamond-cut;14k Yellow gold;Lobster;Special lengths avail.;
Polished back;Fold-over;Textured;IP-plated;IP black-plated;
Enamel;Beveled Edge;Polished edges;Brushed center;
Polished back;Flat edge;Textured;IP-plated;IP black-plated;Polished edges;
Flat back;Enamel;Beveled Edge;Brushed center;
Flat back;Polished back;Diamond;Flat edge;Textured;IP-plated;IP black-plated;Polished edges;1 stone;
Polished back;Flat edge;Textured;IP-plated;IP black-plated;Polished edges;
Polished;IP-plated;Opens;IP rose-plated;IP yellow-plated;
Polished;10K Yellow gold;Lobster;Lightweight;
Solid;Polished;10K Yellow gold;Lobster;Box;
Casted;Polished;10K Yellow gold;CZ;
Polished;10K Yellow gold;CZ;
Polished;10K Yellow gold;Open back;
Diamond-cut;Polished;10K Yellow gold;Rhodium;Textured back;
;
Polished;Spring Ring;10K White gold;
Polished;Spring Ring;10K White gold;
Solid;Polished;10K Yellow gold;Spring Ring;
Solid;Polished;10K Yellow gold;Spring Ring;
Solid;Polished;10K Yellow gold;Spring Ring;
Solid;Polished;10K Yellow gold;Spring Ring;
Polished;10K Yellow gold;Box;Spring Ring;
Polished;10K Yellow gold;Box;Spring Ring;
Solid;10K Yellow gold;Spring Ring;
Solid;10K Yellow gold;Spring Ring;
Solid;10K Yellow gold;Spring Ring;
Polished;Box;Spring Ring;10K White gold;
Solid;Polished;Box;Spring Ring;10K White gold;
Solid;Polished;Lobster;Box;10K White gold;
Diamond-cut;Polished;Spring Ring;10K White gold;
Solid;14K White gold;Spring Ring;
Solid;14k Yellow gold;Spring Ring;
Polished;10K Yellow gold;Hinged post;Hollow tube;
10K Two-tone;Hinged post;Textured;Twisted;
14k Yellow gold;Lobster;18" chain;
Polished;14K White gold;Spring Ring;Box chain;
Solid;Diamond-cut;14K White gold;Lobster;
Polished;14K White gold;Lobster;Box chain;18" chain;
14K White gold;Lobster;18" chain;
Polished;14k Yellow gold;Post;
Polished;14k Yellow gold;Post;
Diamond-cut;14k Yellow gold;Lobster;
Diamond-cut;14K White gold;Lobster;
Diamond-cut;14K White gold;Lobster;18" chain;
Polished;14K White gold;Lobster;Box chain;
Polished;14K Two-tone;Fancy lobster;Textured;Diamond Cut;
Polished;14k Yellow gold;Hinged post;
Polished;14k Yellow gold;Lobster;Box chain;18" chain;
Polished;10K Yellow gold;Slip on;
Solid;Polished;14K White gold;Spring Ring;
Solid;Polished;14k Yellow gold;Spring Ring;
Solid;Polished;14k Yellow gold;Spring Ring;
Solid;Polished;14K White gold;Spring Ring;
Solid;Polished;14k Yellow gold;Spring Ring;
Solid;Polished;14K White gold;Spring Ring;
Solid;Polished;14K White gold;Spring Ring;
Solid;Polished;14K White gold;Spring Ring;
Solid;Polished;14k Yellow gold;Spring Ring;
Solid;Polished;14k Yellow gold;Spring Ring;
Solid;Polished;14K White gold;Spring Ring;
Solid;Polished;14K White gold;Spring Ring;
Solid;Polished;14K White gold;Spring Ring;
;
Polished;14k Yellow gold;Spring Ring;Box chain;
Solid;Polished;14k Yellow gold;Spring Ring;
Casted;Polished;14k Yellow gold;Lobster;
Diamond-cut;Polished;14K Two-tone;Spring Ring;
Diamond-cut;Polished;Satin;14K White gold;Lobster;
Diamond-cut;Polished;Satin;14k Yellow gold;Lobster;
Diamond-cut;Polished;14k Yellow gold;Spring Ring;Adjustable;
Polished;14k Yellow gold;Spring Ring;Adjustable;
Polished;14K White gold;Spring Ring;Adjustable;
Diamond-cut;Polished;14K Tri-color;Spring Ring;Adjustable;
Polished;14k Yellow gold;Spring Ring;1" extender;Adjustable;
Diamond-cut;Polished;14K White gold;Hollow;Spring Ring;1" extender;Adjustable;
Polished;14K Two-tone;Spring Ring;1" extender;Adjustable;
Polished;14K White gold;Spring Ring;1" extender;Adjustable;Diamond Cut;
Diamond-cut;Polished;14K Two-tone;Spring Ring;1" extender;Adjustable;3-strand;
Polished;14K White gold;Spring Ring;1" extender;Adjustable;
Polished;14k Yellow gold;Spring Ring;1" extender;Diamond Cut;
Polished;14K Two-tone;Spring Ring;1" extender;
Polished;14k Yellow gold;Spring Ring;1" extender;
Polished;14k Yellow gold;Spring Ring;
Polished;14K Tri-color;Spring Ring;1" extender;
Polished;14k Yellow gold;Spring Ring;1" extender;
Polished;14K Two-tone;Spring Ring;1" extender;Diamond Cut;
Polished;14k Yellow gold;Stamped;Spring Ring;
Polished;14k Yellow gold;Stamped;Spring Ring;1" extender;
Casted;Polished;14k Yellow gold;Spring Ring;1" extender;
Casted;Diamond-cut;Polished;14K Two-tone;Spring Ring;1" extender;
14k Yellow gold;Spring Ring;1" extender;
Polished;14k Yellow gold;Lobster;
Polished;14K White gold;Hollow;Fancy lobster;
Polished;14K Two-tone;Hollow;Spring Ring;
Solid;14k Yellow gold;Lobster;
Solid;14k Yellow gold;Lobster;
Polished;14k Yellow gold;Hollow;Spring Ring;
Polished;14k Yellow gold;Hollow;Spring Ring;
Solid;14k Yellow gold;Lobster;
Solid;14k Yellow gold;Lobster;
Solid;14k Yellow gold;Lobster;
Solid;14k Yellow gold;Lobster;
Polished;14k Yellow gold;Lobster;
Polished;Satin;Lobster;14K Yellow gold & rhodium;Rhodium;
Polished;14k Yellow gold;Lobster;
Diamond-cut;14k Yellow gold;Enamel;Spring Ring;
Polished;14k Yellow gold;Hollow;Lobster;
Casted;Polished;14k Yellow gold;Avail. in 14k white gold;Prong set;
Polished;14K White gold;Hollow;Lobster;Lightweight;
Polished;14k Yellow gold;Hollow;Lobster;Lightweight;
Polished;14k Yellow gold;Hollow;Lightweight;
Polished;14k Yellow gold;Hollow;Lobster;Lightweight;Flat;
Polished;14k Yellow gold;Hollow;Lobster;Lightweight;
Polished;14k Yellow gold;Hollow;Lobster;Semi Solid;
Polished;14k Yellow gold;Lobster;
Silver-tone;
Crystal;Silver-tone;
24k gold-plated;Natural;Gift Boxed;Lacquered finish;
24k gold-plated;Natural;Gift Boxed;Lacquered finish;
Gold-tone;Natural;Gift Boxed;Lacquered finish;
Natural;Gift Boxed;Lacquered finish;
24k gold-plated;Natural;Gift Boxed;
Natural;Gift Boxed;Copper-tone;
24k gold-plated;Gift Boxed;
24k gold-plated;Natural;Gift Boxed;
Natural;Gift Boxed;Copper-tone;
24k gold-plated;Natural;Gift Boxed;
Natural;Gift Boxed;Copper-tone;
Crystal;Silver-tone;
Silver-tone;
Crystal;Silver-tone;
Porcelain;Crystal;Gold-tone;
Crystal;Rose-tone;
Fancy lobster;Crystal;Shepherd hook;Silver-tone;3" Extension;Decorative Toggle;
Fancy lobster;Crystal;Shepherd hook;Silver-tone;3" Extension;Decorative Toggle;
Crystal;Silver-tone;
Crystal;Gold-tone;Simulated pearl;
Crystal;Silver-tone;Glass crystal;
Gold-tone;Glass crystal;
Black Plating;Glass crystal;
Metal;Glass;Black Plating;
Silver-tone;Simulated pearl;Glass crystal;
Silver-tone;Glass crystal;
Gold-tone;Simulated pearl;Glass crystal;
Gold-tone;Glass crystal;
Crystal;Silver-tone;Stretch;
Crystal;Silver-tone;
Crystal;Gold-tone;
Crystal;Gold-tone;
Crystal;Gold-tone;Glass crystal;
Crystal;Silver-tone;
Crystal;Gold-tone;
Black Plating;Acrylic;Black crystal;
Black Plating;Black crystal;
Black Plating;Glass crystal;
Acrylic crystal;Black Plating;Black crystal;
Silver-tone;
Crystal;Silver-tone;
Crystal;Silver-tone;
Crystal;Silver-tone;
Crystal;Silver-tone;
Crystal;Gold-tone;Simulated pearl;
Crystal;Gold-tone;
Crystal;Gold-tone;Simulated pearl;
Crystal;Gold-tone;Simulated pearl;
Gold-tone;Acrylic;Cameo;
Natural;Gift Boxed;Lacquered finish;
Natural;Gift Boxed;Lacquered finish;
Natural;Gift Boxed;Lacquered finish;
Natural;Gift Boxed;Lacquered finish;
Natural;Gift Boxed;Lacquered finish;
Natural;Gift Boxed;Lacquered finish;
Natural;Gift Boxed;Lacquered finish;
Natural;Gift Boxed;Lacquered finish;
Natural;Gift Boxed;Lacquered finish;
Natural;Gift Boxed;Lacquered finish;
Natural;Gift Boxed;Lacquered finish;
Natural;Gift Boxed;Lacquered finish;
Natural;Gift Boxed;Lacquered finish;
Natural;Gift Boxed;Lacquered finish;
Natural;Gift Boxed;Lacquered finish;
Natural;Gift Boxed;Lacquered finish;
Natural;Gift Boxed;Lacquered finish;
Natural;Gift Boxed;Lacquered finish;
Crystal;Silver-tone;
Polished;14k Yellow gold;Engravable;Lobster;
Polished;14k Yellow gold;Spring Ring;Not engraveable;Textured;Two-tone;
Solid;Polished;14k Yellow gold;Lobster;
Solid;Polished;14k Yellow gold;Lobster;
Solid;Polished;14k Yellow gold;Lobster;
Polished;14k Yellow gold;Lobster;
Polished;14k Yellow gold;Lobster;
Polished;14k Yellow gold;Lobster;
Polished;14k Yellow gold;Lobster;
Brass;Freshwater cultured pearl;Toggle;Gold-tone;Protective nano coat;
Polished;14k Yellow gold;Hollow;Hinged;Safety clasp;
Polished;14k Yellow gold;Hinged;Safety clasp;Twisted;
Solid;Casted;Polished;14k Yellow gold;Not engraveable;Textured back;
Polished;3-D;14k Yellow gold;Hollow;
Polished;3-D;14k Yellow gold;Hollow;
Polished;3-D;14k Yellow gold;Hollow;
Solid;Casted;Polished;14k Yellow gold;Not engraveable;Textured back;
Polished;3-D;14k Yellow gold;Hollow;
Polished;3-D;14k Yellow gold;Hollow;
Solid;Polished;14k Yellow gold;
Polished;3-D;14k Yellow gold;Hollow;
Polished;14k Yellow gold;Hollow;
Solid;Diamond-cut;Polished;Die struck;14k Yellow gold;Textured;Textured back;
Polished;14K White gold;Flat back;
;
Solid;Polished;14k Yellow gold;Lobster;Concave;
;
;
Box catch;Platinum-plated;Swarovski Elements;Metal;
Platinum-plated;Swarovski Elements;Metal;
Enamel;Swarovski Elements;Metal;24k gold-plated;
Swarovski Elements;Metal;24k gold-plated;
Swarovski Elements;Metal;24k gold-plated;Briolette cut;
Swarovski Elements;Rhodium-plated;Metal;
Spring Ring;Swarovski Elements;Metal;24k gold-plated;Detachable;
Metal;24k gold-plated;
Swarovski Elements;Metal;24k gold-plated;
Swarovski Elements;Metal;24k gold-plated;
Swarovski Elements;Metal;24k gold-plated;
Enamel;Fancy lobster;Swarovski Elements;Metal;24k gold-plated;3" Extension;Simulated pearl;
Fold-over;Swarovski Elements;Rhodium-plated;Metal;1" extender;
Synthetic;Swarovski Elements;Rhodium-plated;Metal;
Swarovski Elements;Metal;24k gold-plated;Simulated pearl;
Slip on;18k gold-plated;Swarovski Elements;Metal;
Slip on;18k gold-plated;Swarovski Elements;Metal;
Lobster;CZ;18k gold-plated;Swarovski Elements;2" extension;
Solid;Casted;Polished;14K White gold;Textured back;
Casted;Polished;14k Yellow gold;
Casted;Polished;14K White gold;
Polished;3-D;14k Yellow gold;Hollow;
Polished;14k Yellow gold;Milgrain;
Solid;Casted;Polished;14K White gold;
Solid;Casted;Polished;14K White gold;Open back;
Solid;Casted;Polished;14k Yellow gold;Flat back;
Solid;Casted;Polished;14K White gold;Flat back;
Polished;3-D;14K White gold;Hollow;
Solid;Casted;Polished;14k Yellow gold;Open back;
Polished;14k Yellow gold;Slip on;Round;Hollow tube;
Polished;14k Yellow gold;Slip on;Round;Hollow tube;
Polished;14k Yellow gold;Hollow;Slip on;
Diamond-cut;Polished;14k Yellow gold;Hollow;Slip on;
Polished;14k Yellow gold;Hinged;Safety clasp;Round;
Solid;Polished;14k Yellow gold;Engravable;Spring Ring;
Solid;Polished;14k Yellow gold;Engravable;Lobster;
Polished;Fancy lobster;Titanium;20" Chain;Stainless steel chain;
Polished;Fancy lobster;Titanium;Stainless steel chain;Black titanium;
Polished;Fancy lobster;Titanium;20" Chain;Cross;Stainless steel chain;
Polished;Titanium;Black titanium;
Polished;Titanium;Brushed center;
Polished;Titanium;Brushed center;
Polished;Titanium;Brushed center;
Polished;Titanium;Brushed center;
Polished;Titanium;Black titanium;
Polished;Titanium;Black titanium;
Polished;Titanium;Black titanium;
Polished;Sterling silver;Fancy lobster;Turquoise;Dangle;Adjustable;
Polished;Lobster;Sterling silver;Box chain;Adjustable;
Polished;Lobster;Sterling silver;Adjustable;Cable chain;
Diamond-cut;Polished;Lobster;Sterling silver;Adjustable;
Polished;Lobster;Sterling silver;Box chain;Rhodium-plated;Adjustable;
Polished;Sterling silver;Shepherd hook;Dangle;Rose-tone;Metal;Flash gold-plated;
Polished;14k Yellow gold;Reversible;Freshwater cultured pearl;Screw back;
Polished;14k Yellow gold;Hinged post;
Polished;14k Yellow gold;
Polished;14k Yellow gold;Hollow;Slip on;
Polished;14k Yellow gold;
Solid;Satin;Engravable;Lifetime warranty;Rhodium-plated;Patterned;Gift Boxed;
Solid;Polished;Engravable (front only);Gold-plated;Lifetime warranty;Gift Boxed;
Solid;Polished;Engravable (front only);Lifetime warranty;Rhodium-plated;Gift Boxed;
Solid;Diamond-cut;Engravable (front only);Gold-plated;Lifetime warranty;Diamond accent;Polished & satin;Gift Boxed;
Solid;Diamond-cut;Engravable (front only);Lifetime warranty;Diamond accent;Rhodium-plated;Polished & satin;Gift Boxed;
Solid;Diamond-cut;Satin;Engravable;Polished back;Lifetime warranty;Rhodium-plated;Gift Boxed;
Solid;Polished;Engravable;Lifetime warranty;Rhodium-plated;Patterned;Gift Boxed;
Solid;Polished;Engravable;Lifetime warranty;Rhodium-plated;Patterned;Gift Boxed;
Solid;Polished;Engravable;Lifetime warranty;Rhodium-plated;Patterned;Gift Boxed;
Solid;Polished;Engravable;Gold-plated;Lifetime warranty;Patterned;Gift Boxed;
Solid;Polished;Engravable;Epoxy resin;Gold-plated;Lifetime warranty;Gift Boxed;
Solid;Polished;Engravable;Epoxy resin;Lifetime warranty;Rhodium-plated;Gift Boxed;
Solid;Polished;Engravable;Lifetime warranty;Rhodium-plated;Patterned;Gift Boxed;
Solid;Polished;Engravable;Gold-plated;Lifetime warranty;Patterned;Gift Boxed;
Solid;Polished;Engravable;Lifetime warranty;Rhodium-plated;Patterned;Gift Boxed;
Solid;Polished;Engravable;Lifetime warranty;Rhodium-plated;Patterned;Gift Boxed;
Solid;Polished;Hinged;Engravable (front only);Lifetime warranty;Rhodium-plated;Gift Boxed;
Solid;Polished;Hinged;Engravable (front only);Gold-plated;Lifetime warranty;Gift Boxed;
Solid;Polished;Hinged;Engravable (front only);Lifetime warranty;Rhodium-plated;Patterned;Gift Boxed;
Solid;Polished;Hinged;Engravable (front only);Lifetime warranty;Rhodium-plated;Patterned;Gift Boxed;
Solid;Diamond-cut;Hinged;Engravable (front only);Gold-plated;Lifetime warranty;Diamond accent;Polished & satin;Gift Boxed;
Solid;Diamond-cut;Hinged;Engravable (front only);Lifetime warranty;Diamond accent;Rhodium-plated;Polished & satin;Gift Boxed;
Polished;Hinged;Engravable (front only);Gold-plated;Lifetime warranty;Gift Boxed;
Solid;Polished;Hinged;Engravable (front only);Lifetime warranty;Rhodium-plated;Gift Boxed;
Solid;Hinged;Engravable;Textured;Lifetime warranty;Rhodium-plated;Polished & satin;Gift Boxed;
Solid;Polished;Hinged;Engravable (front only);Lifetime warranty;Rhodium-plated;Patterned;Gift Boxed;
Solid;Polished;Hinged;Engravable (front only);Lifetime warranty;Rhodium-plated;Patterned;Gift Boxed;
Solid;Polished;Hinged;Engravable (front only);Gold-plated;Lifetime warranty;Patterned;Gift Boxed;
Silver-tone;Hypo-allergenic plating;
Solid;Satin;Engravable (front only);Gold-plated;Lifetime warranty;Gift Boxed;
Solid;Satin;Engravable (front only);Lifetime warranty;Rhodium-plated;Gift Boxed;
Solid;Engravable;Polished back;Florentine;
Solid;Polished;Engravable;Lifetime warranty;Rhodium-plated;Patterned;Gift Boxed;
Solid;Diamond-cut;Satin;Engravable;Polished back;Gold-plated;Lifetime warranty;Gift Boxed;
Solid;Satin;Engravable;Polished back;Lifetime warranty;Rhodium-plated;Gift Boxed;
Solid;Diamond-cut;Satin;Hinged;Engravable;Polished back;Lifetime warranty;Rhodium-plated;Gift Boxed;
Solid;Polished;Engravable;Lifetime warranty;Rhodium-plated;Gift Boxed;
Solid;Polished;Engravable;Gold-plated;Lifetime warranty;Patterned;Gift Boxed;
Solid;Polished;Engravable;Lifetime warranty;Rhodium-plated;Patterned;Gift Boxed;
Solid;Polished;Engravable;Gold-plated;Lifetime warranty;Patterned;Gift Boxed;
Solid;Polished;Engravable;Gold-plated;Lifetime warranty;Patterned;Gift Boxed;
Solid;Polished;Engravable;Lifetime warranty;Rhodium-plated;Patterned;Gift Boxed;
Solid;Polished;Engravable;Gold-plated;Lifetime warranty;Patterned;Gift Boxed;
Solid;Polished;Engravable;Lifetime warranty;Rhodium-plated;Patterned;Gift Boxed;
Solid;Hinged;Engravable;Textured;Lifetime warranty;Rhodium-plated;Polished & satin;Gift Boxed;
Solid;Polished;Engravable;Stainless Steel;Lifetime warranty;Rhodium-plated;Gift Boxed;Double sided;
Solid;Satin;Engravable;Stainless Steel;Lifetime warranty;Rhodium-plated;Gift Boxed;Double sided;
14k Yellow gold;Flat back;Hollow;
Casted;Polished;14k Yellow gold;
Casted;Polished;14k Yellow gold;
Solid;Polished;14k Yellow gold;
Solid;Casted;Polished;14K Two-tone;
;
;
CZ;Lifetime warranty;Rhodium-plated;Gift Boxed;
Solid;Polished;Hinged;Engravable;Lifetime warranty;Rhodium-plated;Patterned;Gift Boxed;
Solid;Polished;Engravable;Gold-plated;Lifetime warranty;Patterned;Gift Boxed;
Solid;Polished;Engravable;Lifetime warranty;Rhodium-plated;Patterned;Gift Boxed;
Solid;Engravable;Lifetime warranty;Rhodium-plated;Patterned;Gift Boxed;
Solid;Polished;Engravable;Lifetime warranty;Rhodium-plated;Patterned;Gift Boxed;
Solid;Polished;Engravable;Lifetime warranty;Rhodium-plated;Patterned;Gift Boxed;
Polished;14K Yellow gold & rhodium;Textured;White;Rose rhodium;Hinged hoop;Tri-color;
Polished;14K White gold;Textured;Hinged hoop;
Polished;14K White gold;Diamond Cut;Hinged hoop;
Polished;14K Two-tone;Fancy lobster;1" extender;
Polished;14K Two-tone;Fancy lobster;
Polished;14k Yellow gold;Lobster;1" extender;
Polished;14k Yellow gold;Fancy lobster;
Polished;Brass;Silver-tone;Protective nano coat;
Polished;Brass;Silver-tone;Protective nano coat;
Polished;Brass;Gold-tone;Protective nano coat;
Polished;Brass;Gold-tone;Protective nano coat;
Polished;14K White gold;Spring Ring;
Polished;14k Yellow gold;Spring Ring;
Polished;14k Yellow gold;Spring Ring;
Polished;14k Yellow gold;Spring Ring;
Solid;Polished;14K White gold;Spring Ring;
Solid;Polished;14k Yellow gold;Spring Ring;
Solid;Diamond-cut;Polished;14k Yellow gold;Spring Ring;
Solid;Diamond-cut;Polished;14k Yellow gold;Spring Ring;
Polished;14K White gold;Lobster;
Diamond-cut;Polished;14k Yellow gold;Lobster;
Diamond-cut;Polished;14k Yellow gold;Lobster;
Polished;14K White gold;Spring Ring;
Diamond-cut;Polished;14K White gold;Lobster;
Diamond-cut;Polished;14K White gold;Lobster;
Diamond-cut;Polished;14K White gold;Lobster;
Diamond-cut;Polished;14K White gold;Spring Ring;
Diamond-cut;Polished;14K White gold;Spring Ring;
Diamond-cut;Polished;14K White gold;Lobster;
Diamond-cut;Polished;14K White gold;Lobster;
Diamond-cut;Polished;14K White gold;Lobster;
Solid;Diamond-cut;14K White gold;Lobster;
Solid;Diamond-cut;14K White gold;Lobster;
Solid;14k Yellow gold;Lobster;
Solid;Diamond-cut;14k Yellow gold;Spring Ring;
Solid;Diamond-cut;14K White gold;Spring Ring;
Diamond-cut;Polished;14k Yellow gold;Lobster;
Diamond-cut;Polished;14k Yellow gold;Lobster;
Diamond-cut;Polished;14k Yellow gold;Lobster;
Solid;Polished;14k Yellow gold;Spring Ring;
Solid;Polished;14k Yellow gold;Lobster;
Solid;Polished;14k Yellow gold;Lobster;
Solid;Diamond-cut;14K White gold;Spring Ring;
Solid;Diamond-cut;14K White gold;Spring Ring;
Solid;Diamond-cut;14K White gold;Lobster;
Solid;Diamond-cut;14K White gold;Lobster;
Solid;Diamond-cut;14K White gold;Lobster;
Solid;Diamond-cut;14K White gold;Lobster;
Solid;Diamond-cut;14k Yellow gold;Lobster;
Solid;Diamond-cut;14k Yellow gold;Lobster;
Solid;Diamond-cut;14k Yellow gold;Lobster;
Solid;Diamond-cut;14k Yellow gold;Lobster;
Solid;Polished;14K White gold;Lobster;
Solid;Polished;14K White gold;Lobster;
Solid;Polished;14k Yellow gold;Lobster;
Polished;14k Yellow gold;Spring Ring;
Polished;14k Yellow gold;Spring Ring;
Polished;14k Yellow gold;Spring Ring;
Solid;14K White gold;Lobster;Special lengths avail.;
Solid;14k Yellow gold;Lobster;Special lengths avail.;
Solid;Diamond-cut;14K White gold;Lobster;
Solid;14K White gold;Lobster;Special lengths avail.;
Solid;Polished;14k Yellow gold;Spring Ring;
Diamond-cut;Polished;14k Yellow gold;Spring Ring;
Diamond-cut;Polished;14k Yellow gold;Spring Ring;
Diamond-cut;Polished;14k Yellow gold;Lobster;
Diamond-cut;Polished;14k Yellow gold;Lobster;
Solid;Polished;14k Yellow gold;Spring Ring;
Solid;Polished;14k Yellow gold;Spring Ring;
Solid;Polished;14k Yellow gold;Spring Ring;
Solid;Polished;14k Yellow gold;Lobster;
Solid;Polished;14k Yellow gold;Lobster;
Solid;Polished;14k Yellow gold;Lobster;
Solid;Polished;14k Yellow gold;Lobster;
Solid;Polished;14K White gold;Lobster;
Solid;Polished;14K White gold;Lobster;
Solid;Polished;14K White gold;Lobster;
Solid;Polished;14K White gold;Spring Ring;
Solid;Polished;14K White gold;Lobster;
Solid;Polished;14K White gold;Lobster;
Solid;Polished;14K White gold;Lobster;
Solid;Diamond-cut;14k Yellow gold;Spring Ring;
Solid;Polished;14K White gold;Lobster;
Solid;Diamond-cut;14k Yellow gold;Spring Ring;
Polished;Brass;Swarovski Elements;Silver-tone;Protective nano coat;
Polished;Brass;Swarovski Elements;Silver-tone;Protective nano coat;
Polished;Brass;Gold-tone;Swarovski Elements;Protective nano coat;
Solid;Casted;Polished;Open back;Lobster;Sterling silver;
Solid;Casted;Polished;Lobster;Sterling silver;
Solid;Casted;Polished;Lobster;Sterling silver;
Polished;Sterling silver;Fancy lobster;
Solid;Polished;Lobster;Sterling silver;Flat;
Solid;Polished;Lobster;Spring Ring;Sterling silver;
Solid;Polished;Open back;Engravable;Sterling silver;Cuff;
Polished;Sterling silver;Slip on;Round edge;
Polished;Flat back;Hollow;Hinged;Sterling silver;Safety clasp;
Solid;Polished;Flat back;Sterling silver;Slip on;Round;
Solid;Polished;Flat back;Sterling silver;Slip on;
Solid;Polished;Flat back;Sterling silver;Slip on;
Polished;Lobster;Sterling silver;Freshwater cultured pearl;
Diamond-cut;Polished;Flat back;Hollow;Hinged;Sterling silver;Box catch;Box chain;
Solid;Casted;Polished;Sterling silver;Cuff;
Polished;Flat back;Hollow;Hinged;Box;Sterling silver;
Solid;Polished;Sterling silver;Flexible;
Solid;Polished;Sterling silver;Flexible;Engravable (front only);
Polished;Hollow;Sterling silver;Cuff;Round edge;
Polished;Sterling silver;Slip on;Cuff;Open;
Polished;Sterling silver;Slip on;Open;
Polished;Sterling silver;Rhodium-plated;Adjustable;Diamond Cut;
Diamond-cut;Polished;Sterling silver;Rhodium-plated;Adjustable;
Polished;Flat back;Sterling silver;Not engraveable by QG;Opens;Holds 2 photos;
Solid;Polished;Flat back;Engravable;Sterling silver;Cuff;
Solid;Polished;Sterling silver;Screw top;
Solid;Polished;Sterling silver;Screw top;
Solid;Polished;Synthetic;Screw top;
Solid;Polished;Sterling silver;Screw top;
Solid;Polished;Sterling silver;Screw top;
Solid;Polished;Sterling silver;Screw top;
Solid;Polished;Sterling silver;Screw top;
Spring Ring;Sterling silver;Box chain;Octagon;Diamond Cut;
Diamond-cut;Spring Ring;Sterling silver;Box chain;Octagon;
Solid;Polished;Sterling silver;Screw top;
Solid;Polished;Sterling silver;Screw top;
Solid;Polished;Sterling silver;Screw top;
Solid;Polished;Spring Ring;Sterling silver;Box chain;
Solid;Polished;Spring Ring;Sterling silver;Box chain;
Solid;Polished;Spring Ring;Sterling silver;Box chain;
Solid;Polished;Spring Ring;Sterling silver;Box chain;
Polished;Spring Ring;Sterling silver;Box chain;
Polished;Spring Ring;Sterling silver;Box chain;
Polished;Spring Ring;Sterling silver;Box chain;
Polished;Spring Ring;Sterling silver;Box chain;
Polished;Spring Ring;Sterling silver;Box chain;
Solid;Polished;Spring Ring;Sterling silver;
Solid;Polished;Spring Ring;Sterling silver;Box chain;
Solid;Polished;Spring Ring;Sterling silver;
Solid;Polished;Spring Ring;
Polished;Spring Ring;E-coated;
Polished;Spring Ring;Sterling silver;Flash gold-plated;
Spring Ring;Sterling silver;Box chain;Rhodium-plated;2" extension;
Polished;Spring Ring;Sterling silver;Box chain;
Solid;Polished;Spring Ring;Sterling silver;
Solid;Polished;Spring Ring;Sterling silver;
Solid;Polished;Spring Ring;Sterling silver;
Solid;Polished;Spring Ring;Sterling silver;
Solid;Polished;Spring Ring;Sterling silver;
Polished;Lobster;Sterling silver;
Polished;Lobster;Sterling silver;
Polished;Lobster;Sterling silver;
Polished;Lobster;Sterling silver;
Solid;Polished;Spring Ring;
Polished;Lobster;Sterling silver;
Solid;Polished;Lobster;Sterling silver;
Solid;Polished;Lobster;Sterling silver;
Solid;Polished;Lobster;Sterling silver;
Solid;Polished;Lobster;Sterling silver;
Solid;Polished;Lobster;Sterling silver;
Solid;Polished;Lobster;Sterling silver;
Solid;Polished;Lobster;Sterling silver;
Solid;Polished;Lobster;Sterling silver;
Solid;Polished;Lobster;Sterling silver;
Solid;Polished;Lobster;Sterling silver;
Solid;Casted;Polished;Open back;Sterling silver;Textured back;Fits up to 3mm;
Solid;Casted;Polished;Sterling silver;
Casted;Polished;Sterling silver;CZ;Moveable;Fits up to 3mm;Two piece;
Casted;Polished;Sterling silver;
Solid;Casted;Polished;Flat back;Sterling silver;Not engraveable;
Solid;Casted;Polished;Flat back;Sterling silver;
Solid;Casted;Polished;Sterling silver;
Solid;Casted;Polished;Open back;Sterling silver;Fits up to 3mm;
Solid;Polished;Flat back;Sterling silver;
Solid;Polished;Sterling silver;
Solid;Casted;Sterling silver;
Solid;Flat back;Antique finish;Sterling silver;
Solid;Polished;Engravable;Sterling silver;Reversible;
Solid;Polished;Flat back;Antique finish;Sterling silver;
Solid;Casted;Die struck;Antique finish;Sterling silver;Reversible;
Solid;Satin;Antique finish;Sterling silver;Engravable (back only);
Solid;Satin;Die struck;Antique finish;Sterling silver;Engravable (back only);
Solid;Satin;Die struck;Antique finish;Sterling silver;Engravable (back only);
Solid;Polished;Satin;Engravable;Antique finish;Sterling silver;
Solid;Satin;Die struck;Engravable;Antique finish;Sterling silver;
Solid;Satin;Die struck;Engravable;Antique finish;Sterling silver;
Solid;Satin;Die struck;Engravable;Antique finish;Sterling silver;
Solid;Satin;Die struck;Antique finish;Sterling silver;Engravable (back only);
Solid;Satin;Die struck;Engravable;Antique finish;Sterling silver;
Solid;Casted;Polished;Engravable;Sterling silver;Heart;Fits up to 3mm;
Solid;Casted;Polished;Open back;Sterling silver;
Solid;Polished;Stamped;Sterling silver;
Solid;Casted;Polished;3-D;Sterling silver;Fits up to 3mm;
Solid;Casted;Polished;Flat back;Sterling silver;
Solid;Casted;Polished;Flat back;Sterling silver;
Solid;Polished;Flat back;Sterling silver;Textured;
Solid;Die struck;Engravable;Antique finish;Sterling silver;Polished & satin;
Solid;Polished;Sterling silver;Not engraveable by QG;Vermeil;
Solid;Polished;Sterling silver;Not engraveable by QG;
Solid;Polished;Sterling silver;CZ;Not engraveable by QG;
Solid;Die struck;Engravable;Antique finish;Sterling silver;Polished & satin;
Solid;Sterling silver;Not engraveable by QG;Polished & satin;
Solid;Polished;Enamel;Sterling silver;Not engraveable by QG;
Solid;Polished;Enamel;Sterling silver;Not engraveable by QG;
Solid;Polished;Sterling silver;Not engraveable by QG;
Solid;Casted;Polished;Sterling silver;
Solid;Satin;Die struck;Antique finish;Sterling silver;Engravable (back only);
Solid;Die struck;Antique finish;Sterling silver;Engravable (back only);Polished & satin;
Solid;Polished;Die struck;Engravable;Antique finish;Sterling silver;
Casted;Polished;Sterling silver;Filigree;
Casted;Diamond-cut;Polished;Sterling silver;Solid Back;
Solid;Casted;Polished;Sterling silver;Cut-out;
Casted;Polished;Satin;Open back;Sterling silver;
Solid;Casted;Diamond-cut;Polished;Sterling silver;
Polished;Open back;Sterling silver;CZ;Rhodium;
Solid;Polished;Sterling silver;
Solid;Polished;Sterling silver;
Polished;3-D;Hollow;Sterling silver;
Solid;Polished;Engravable;Sterling silver;
Polished;Die struck;Sterling silver;Not engraveable;
Solid;Die struck;Engravable;Sterling silver;Polished & satin;
Solid;Polished;Die struck;Sterling silver;Engravable (back only);
Solid;Casted;Polished;Sterling silver;Fits up to 4mm;
Solid;Die struck;Engravable;Antique finish;Sterling silver;
Solid;Satin;Die struck;Engravable;Antique finish;Sterling silver;
Casted;Polished;3-D;Hollow;Sterling silver;Filigree;Heart;Fits up to 3mm;
Solid;Polished;Engravable;Sterling silver;Heart;Flat;Fits up to 3mm;
Solid;Polished;Engravable;Sterling silver;Heart;Flat;Chain slide;
Solid;Polished;Open back;Antique finish;Sterling silver;Not engraveable;
Solid;Polished;3-D;Sterling silver;Fits up to 3mm;
Solid;Polished;3-D;Sterling silver;Fits up to 3mm;
Solid;Polished;3-D;Sterling silver;Fits up to 3mm;
Solid;Polished;3-D;Sterling silver;Fits up to 3mm;
Solid;Polished;Open back;Sterling silver;CZ;Fits up to 3mm;
Solid;Polished;Sterling silver;Glitter enamel;
Solid;Polished;Sterling silver;
Polished;Sterling silver;Fits up to 3mm;
Casted;Polished;Sterling silver;
Polished;Sterling silver;
Solid;Polished;Satin;Sterling silver;Not engraveable by QG;
Solid;Casted;Polished;Sterling silver;Antiqued;
Solid;Polished;Engravable;Polished back;Sterling silver;
Casted;Polished;Sterling silver;Reversible;Flat;
Solid;Polished;Sterling silver;Cut-out;
Solid;Polished;Sterling silver;Acrylic;Fits up to 3mm;
Solid;Polished;Sterling silver;Acrylic;Fits up to 3mm;
Solid;Polished;Sterling silver;Acrylic;Fits up to 3mm;
Solid;Casted;Polished;Sterling silver;Concave;
Casted;Polished;Hollow;Sterling silver;Heart;
Polished;Open back;Sterling silver;
Solid;Polished;Closed back;Enamel;Sterling silver;
Solid;Polished;Sterling silver;
Solid;Casted;Polished;Sterling silver;
Solid;Casted;Polished;Sterling silver;
Solid;Polished;Sterling silver;
Solid;Polished;Polished back;Sterling silver;
Solid;Polished;Flat back;Sterling silver;
Solid;Polished;Flat back;Sterling silver;
Polished;Sterling silver;Cut-out;
Polished;Sterling silver;
Polished;Sterling silver;
Casted;Polished;Sterling silver;
Polished;Sterling silver;Acrylic;
Polished;Enamel;Sterling silver;Gold-plated;
Casted;Sterling silver;Concave;Antiqued;
Solid;Casted;Open back;Sterling silver;Antiqued;
Sterling silver;Antiqued;
Solid;Polished;Sterling silver;
Polished;Sterling silver;Textured;
Solid;Casted;Polished;3-D;Sterling silver;
Polished;Flat back;Sterling silver;Textured back;
Solid;Casted;Polished;Sterling silver;Fits up to 4mm;
Solid;Casted;Polished;Sterling silver;Fits up to 3mm;
Solid;Casted;Polished;Sterling silver;
Polished;Lobster;Sterling silver;
Polished;Lobster;Sterling silver;
Polished;Lobster;Sterling silver;
Polished;Lobster;Sterling silver;
Polished;Lobster;Sterling silver;
Polished;Lobster;Sterling silver;
Polished;Lobster;Sterling silver;
Polished;Lobster;Sterling silver;
Solid;Polished;Lobster;Sterling silver;
;
Solid;Polished;Spring Ring;Sterling silver;
Solid;Polished;Spring Ring;Sterling silver;
Solid;Polished;Spring Ring;Sterling silver;
Solid;Polished;Lobster;Sterling silver;
Solid;Polished;Spring Ring;Sterling silver;
Solid;Polished;Lobster;Sterling silver;
Solid;Polished;Lobster;Sterling silver;
Solid;Polished;Lobster;Sterling silver;
Solid;Polished;Lobster;Sterling silver;
Solid;Polished;Lobster;Sterling silver;
Solid;Polished;Lobster;Sterling silver;
Solid;Polished;Lobster;Sterling silver;
Solid;Polished;Lobster;Sterling silver;
Solid;Polished;Lobster;Sterling silver;
Solid;Polished;Lobster;Sterling silver;
Polished;3-D;Enamel;Sterling silver;Fancy lobster;Rhodium-plated;
Solid;Casted;Polished;Engravable;Lobster;
Solid;Casted;Polished;Engravable;Lobster;
Solid;Casted;Polished;Engravable;Sterling silver;Comfort fit;
Solid;Casted;Polished;Engravable;Sterling silver;Comfort fit;
Solid;Casted;Polished;Engravable;Sterling silver;Comfort fit;
Solid;Casted;Polished;Engravable;Sterling silver;Comfort fit;
Solid;Casted;Polished;Engravable;Sterling silver;Comfort fit;
Solid;Casted;Polished;Engravable;Sterling silver;Comfort fit;
Casted;Polished;Lobster;Sterling silver;
Casted;Polished;Lobster;Sterling silver;
Solid;Polished;Lobster;Sterling silver;
Solid;Polished;Lobster;Sterling silver;
Solid;Polished;Lobster;Sterling silver;
Solid;Polished;Lobster;Sterling silver;
Solid;Polished;Lobster;Sterling silver;
Solid;Polished;Lobster;Sterling silver;
Polished;Lobster;Sterling silver;
Polished;Lobster;Sterling silver;
Polished;Lobster;Sterling silver;
Polished;Spring Ring;Sterling silver;Cable chain;
Polished;Spring Ring;Sterling silver;Cable chain;
Polished;Lobster;Sterling silver;
Polished;Lobster;Sterling silver;Cable chain;
Polished;Lobster;Sterling silver;
Polished;Lobster;Sterling silver;
Lobster;Sterling silver;Rhodium-plated;2" extension;Cable chain;
Polished;Spring Ring;Sterling silver;
Polished;Spring Ring;Sterling silver;
Polished;Spring Ring;Sterling silver;
Solid;Polished;Lobster;
Polished;Lobster;
Polished;Lobster;Sterling silver;
Polished;Lobster;Sterling silver;
Polished;Lobster;Sterling silver;
Polished;Lobster;Sterling silver;
Polished;Lobster;Sterling silver;
Polished;Lobster;Sterling silver;
Solid;Polished;Lobster;Sterling silver;
Solid;Polished;Lobster;Sterling silver;
Solid;Diamond-cut;Polished;Spring Ring;Sterling silver;
Solid;Polished;Spring Ring;Sterling silver;Diamond Cut;
Solid;Polished;Spring Ring;Sterling silver;Diamond Cut;
Solid;Diamond-cut;Polished;Spring Ring;Sterling silver;
Solid;Diamond-cut;Polished;Spring Ring;Sterling silver;
Diamond-cut;Spring Ring;Sterling silver;Rhodium-plated;
Solid;Polished;Spring Ring;Sterling silver;Diamond Cut;
Solid;Polished;Spring Ring;Sterling silver;Diamond Cut;
Solid;Polished;Spring Ring;Sterling silver;Diamond Cut;
Solid;Polished;Spring Ring;Sterling silver;Diamond Cut;
Diamond-cut;Polished;Lobster;Sterling silver;
Solid;Diamond-cut;Polished;Lobster;Sterling silver;
Solid;Diamond-cut;Polished;Lobster;Sterling silver;
Solid;Diamond-cut;Polished;Lobster;Sterling silver;
Solid;Diamond-cut;Polished;Lobster;Sterling silver;
Solid;Diamond-cut;Polished;Lobster;Sterling silver;
Solid;Diamond-cut;Polished;Lobster;Sterling silver;
Solid;Diamond-cut;Polished;Lobster;Sterling silver;
Solid;Diamond-cut;Polished;Lobster;Sterling silver;
Solid;Diamond-cut;Polished;Lobster;Sterling silver;
Solid;Diamond-cut;Polished;Lobster;Sterling silver;
Solid;Diamond-cut;Polished;Lobster;Sterling silver;
Solid;Diamond-cut;Polished;Lobster;Sterling silver;
Solid;Diamond-cut;Polished;Lobster;Sterling silver;
Solid;Diamond-cut;Polished;Lobster;Sterling silver;
Solid;Diamond-cut;Polished;Lobster;Sterling silver;
Solid;Diamond-cut;Polished;Lobster;Sterling silver;
Solid;Diamond-cut;Polished;Lobster;Sterling silver;
Solid;Diamond-cut;Polished;Lobster;Sterling silver;
Solid;Diamond-cut;Polished;Lobster;Sterling silver;
Polished;Hinged;Sterling silver;Platinum-plated;Diamond accent;Diamond dust accents;Patented;Diamond Mystique;
Solid;Diamond-cut;Polished;Lobster;Sterling silver;
Solid;Polished;Lobster;Sterling silver;Diamond Cut;
Solid;Diamond-cut;Polished;Lobster;Sterling silver;
Solid;Polished;Lobster;Sterling silver;Diamond Cut;
Polished;Sterling silver;Freshwater cultured pearl;Diamond;Rhodium-plated;
Polished;Open back;Sterling silver;Freshwater cultured pearl;Diamond;Rhodium-plated;
Polished;Post;Sterling silver;CZ;Round;Snap setting;Radiant Cut;
Polished;Post;Sterling silver;CZ;Round;Snap setting;Radiant Cut;
Polished;Post;Sterling silver;CZ;Round;Snap setting;Radiant Cut;
Polished;Post;Sterling silver;CZ;Round;Snap setting;Radiant Cut;
Polished;Post;Sterling silver;CZ;Round;Snap setting;Radiant Cut;
Polished;Post;Sterling silver;CZ;Round;Snap setting;Radiant Cut;
Solid;Casted;Polished;Post;
;
Casted;Polished;Post;Sterling silver;
;
Polished;Post;Sterling silver;Freshwater cultured pearl;
Casted;Polished;Post;Sterling silver;CZ;Rhodium-plated;
Casted;Polished;Post;Sterling silver;CZ;Rhodium-plated;
Polished;Post;Sterling silver;Cross;
Polished;Post;Sterling silver;
Polished;Post;Sterling silver;
Polished;Post;Sterling silver;
Polished;Post;Sterling silver;
Polished;Post;Sterling silver;
Polished;Post;Sterling silver;
Polished;Post;Sterling silver;Round;
Polished;Post;Sterling silver;
Polished;Post;Sterling silver;
Casted;Polished;Post;Sterling silver;CZ;Rhodium-plated;
Casted;Antique finish;Sterling silver;Shepherd hook;Created opal;Rhodium-plated;
Post;Sterling silver;Freshwater cultured pearl;
Post;Sterling silver;Freshwater cultured pearl;
Polished;Sterling silver;Freshwater cultured pearl;Shepherd hook;Dangle;
Solid;Casted;Polished;Sterling silver;Shepherd hook;
Post;Sterling silver;CZ;Radiant Cut;Basket setting;
Post;Sterling silver;CZ;Radiant Cut;Basket setting;
Post;Sterling silver;CZ;Radiant Cut;Basket setting;
Post;Sterling silver;CZ;Radiant Cut;Basket setting;
Post;Sterling silver;CZ;Prong set;Princess Cut;Basket setting;
Post;Sterling silver;CZ;Prong set;Princess Cut;Basket setting;
Post;Sterling silver;CZ;Prong set;Princess Cut;Basket setting;
Diamond-cut;Satin;Post;Sterling silver;
Diamond-cut;Polished;Sterling silver;Hollow tube;Rhodium-plated;
Diamond-cut;Polished;Sterling silver;Hollow tube;Rhodium-plated;
Polished;Hollow;Hinged;Sterling silver;
Polished;Sterling silver;Threader;
Polished;Sterling silver;Threader;
Polished;Sterling silver;Shepherd hook;Dangle;
Polished;Hinged;Sterling silver;Hollow tube;
Polished;Hinged;Sterling silver;Hollow tube;
Polished;Hinged;Sterling silver;Hollow tube;
Polished;Hinged;Sterling silver;Hollow tube;
Polished;Hinged post;Sterling silver;Hollow tube;Rhodium-plated;
Polished;Hinged post;Sterling silver;Hollow tube;Rhodium-plated;
Polished;Hinged post;Sterling silver;Hollow tube;Rhodium-plated;
Polished;Hinged post;Sterling silver;Hollow tube;Rhodium-plated;
Polished;Hinged post;Sterling silver;Hollow tube;Rhodium-plated;
Polished;Hinged post;Sterling silver;Hollow tube;Rhodium-plated;
Polished;Hinged post;Sterling silver;Hollow tube;Rhodium-plated;
Polished;Hinged post;Sterling silver;Hollow tube;Rhodium-plated;
Polished;Hinged post;Sterling silver;Hollow tube;Rhodium-plated;
Diamond-cut;Polished;Satin;Hinged post;Sterling silver;Rhodium-plated;
Polished;Hollow;Hinged;Sterling silver;Rhodium-plated;Square;
Polished;Post;Sterling silver;
Solid;Casted;Polished;Satin;Post;Sterling silver;Heart;
Polished;Sterling silver;Shepherd hook;
Polished;Post;Sterling silver;Rhodium-plated;
Casted;Polished;Satin;Post;Sterling silver;Cross;
Sterling silver;Shepherd hook;Dangle;Handcrafted;Dichroic glass;Color & pattern may vary;
Sterling silver;Shepherd hook;Dangle;Handcrafted;Dichroic glass;Color & pattern may vary;
Lobster;Sterling silver;Shepherd hook;Dichroic glass;Blue;
Polished;Post;Sterling silver;Cross;
Polished;Post;Sterling silver;
Solid;Polished;Post;Sterling silver;
Diamond-cut;Hinged;Sterling silver;
Polished;Post;Sterling silver;CZ;Round;Snap setting;Radiant Cut;
Post;Sterling silver;CZ;Snap setting;Radiant Cut;Square;
Post;Sterling silver;Freshwater cultured pearl;
Post;Sterling silver;Freshwater cultured pearl;
Post;Sterling silver;Freshwater cultured pearl;White;
Post;Sterling silver;Freshwater cultured pearl;White;
Post;Sterling silver;Freshwater cultured pearl;
Post;Spring Ring;Sterling silver;Freshwater cultured pearl;
Post;Sterling silver;Freshwater cultured pearl;White;
Polished;Hinged post;Sterling silver;Rhodium-plated;
Polished;Hinged post;Sterling silver;Rhodium-plated;
Casted;Polished;Post;Sterling silver;CZ;Rhodium-plated;
Polished;Hinged post;Sterling silver;Round;Rhodium-plated;
Polished;Hinged post;Sterling silver;Round;Rhodium-plated;
Polished;Hinged post;Sterling silver;Rhodium-plated;
Polished;Hinged post;Sterling silver;Rhodium-plated;
Polished;Hinged post;Sterling silver;Rhodium-plated;
Polished;Hinged post;Sterling silver;Round;Rhodium-plated;
Polished;Hinged post;Sterling silver;Round;Rhodium-plated;
Polished;Hinged post;Sterling silver;Round;Rhodium-plated;
Polished;Hinged post;Sterling silver;Round;Rhodium-plated;
Hollow;Hinged post;Sterling silver;Rhodium-plated;
Casted;Polished;Post;Sterling silver;CZ;Rhodium-plated;
Polished;Post;Sterling silver;CZ;Round;
Polished;Post;Sterling silver;CZ;Round;
Casted;Polished;Post;Sterling silver;CZ;Rhodium-plated;Chain slide;Hidden bail;
Solid;Polished;Lobster;Sterling silver;
Polished;Spring Ring;Sterling silver;
Spring Ring;Sterling silver;Rhodium-plated;2" extension;
Polished;Lobster;Sterling silver;
Solid;Polished;Lobster;Sterling silver;
Solid;Polished;Sterling silver;
Spring Ring;Sterling silver;
Spring Ring;Sterling silver;
Sterling silver;Fancy lobster;
Spring Ring;Sterling silver;
Solid;Polished;Lobster;Sterling silver;
Polished;Lobster;Sterling silver;
Polished;Lobster;Sterling silver;
Polished;Lobster;Sterling silver;
Polished;Lobster;Sterling silver;
Polished;Lobster;Sterling silver;
Polished;Lobster;Sterling silver;
Polished;Spring Ring;Sterling silver;
Polished;Spring Ring;Sterling silver;
Polished;Spring Ring;Sterling silver;
Polished;Spring Ring;Sterling silver;
Polished;Spring Ring;Sterling silver;
Polished;Spring Ring;Sterling silver;
Polished;Spring Ring;Sterling silver;
Polished;Spring Ring;Sterling silver;
Polished;Lobster;Sterling silver;
Polished;Lobster;Sterling silver;
Polished;Lobster;Sterling silver;
Polished;Lobster;Sterling silver;
Polished;Lobster;Sterling silver;
Polished;Lobster;Sterling silver;
Polished;Lobster;Sterling silver;
Polished;Spring Ring;Sterling silver;
Polished;Spring Ring;Sterling silver;
Polished;Spring Ring;Sterling silver;
Solid;Polished;Spring Ring;Sterling silver;
Solid;Polished;Spring Ring;Sterling silver;
Solid;Polished;Spring Ring;Sterling silver;
Solid;Polished;Spring Ring;Sterling silver;
Solid;Polished;Lobster;Sterling silver;
Solid;Polished;Lobster;Sterling silver;
Solid;Polished;Lobster;Sterling silver;
Solid;Polished;Lobster;Sterling silver;
Solid;Polished;Lobster;Sterling silver;
Solid;Polished;Lobster;Sterling silver;
Solid;Polished;Lobster;Sterling silver;
Solid;Polished;Lobster;Sterling silver;
Solid;Polished;Lobster;Sterling silver;
Solid;Polished;Lobster;Sterling silver;
Solid;Polished;Lobster;Sterling silver;
Solid;Polished;Lobster;Sterling silver;
Solid;Polished;Lobster;Sterling silver;
Solid;Polished;Lobster;Sterling silver;
Solid;Polished;Lobster;Sterling silver;
Solid;Polished;Lobster;Sterling silver;
Solid;Polished;Lobster;Sterling silver;
Solid;Polished;Lobster;Sterling silver;
Solid;Casted;Polished;Lobster;
Solid;Polished;Lobster;Sterling silver;
Solid;Polished;Lobster;Sterling silver;
Solid;Polished;Lobster;Sterling silver;
Solid;Polished;Lobster;Sterling silver;
Solid;Polished;Lobster;Sterling silver;
Solid;Polished;Lobster;Sterling silver;
Solid;Polished;Lobster;Sterling silver;
Casted;Polished;Engravable;Sterling silver;Fancy lobster;
Casted;Polished;Hollow;Engravable;Sterling silver;Toggle;Heart;
Solid;Casted;Polished;Lobster;Sterling silver;
Solid;Casted;Polished;Lobster;Sterling silver;
Solid;Casted;Polished;Lobster;Sterling silver;
Solid;Casted;Polished;Lobster;Sterling silver;
Polished;3-D;Hollow;Lobster;Sterling silver;Adjustable;
Solid;Polished;Flat back;Spring Ring;Sterling silver;Heart;
Polished;3-D;Hollow;Spring Ring;Sterling silver;
Solid;Polished;3-D;Hollow;Spring Ring;Sterling silver;
Polished;3-D;Hollow;Spring Ring;Sterling silver;
Polished;Spring Ring;Sterling silver;
Polished;Sterling silver;Fancy lobster;Adjustable;Beaded Chain;
Solid;Polished;Sterling silver;Fancy lobster;
Solid;Polished;Sterling silver;Fancy lobster;
Lobster;Sterling silver;Rubber;Black;
Lobster;Sterling silver;Rubber;Black;
Lobster;Sterling silver;Rubber;Black;
Solid;Casted;Polished;Lobster;Sterling silver;
Solid;Casted;Polished;Lobster;Sterling silver;
Lobster;Sterling silver;Leather;Black;
Lobster;Sterling silver;Leather;Black;
Lobster;Sterling silver;Leather;Black;
Lobster;Sterling silver;Leather;Black;
Polished;Spring Ring;Sterling silver;
Polished;Spring Ring;Sterling silver;
Polished;Lobster;Sterling silver;
Polished;Lobster;Sterling silver;Heart;
Polished;Lobster;Sterling silver;Box chain;1" extender;
Solid;Polished;Lobster;Sterling silver;
Polished;Lobster;Sterling silver;
Polished;Lobster;Sterling silver;
Polished;Lobster;Sterling silver;
Polished;Lobster;Sterling silver;
Polished;Lobster;Sterling silver;
Polished;Lobster;Sterling silver;
Diamond-cut;Polished;Spring Ring;Sterling silver;
Polished;Sterling silver;Fancy lobster;Heart;
Spring Ring;Sterling silver;Turquoise;Antiqued;
Polished;Spring Ring;Sterling silver;
Polished;Spring Ring;Sterling silver;Rhodolite garnet;
Polished;Sterling silver;Fancy lobster;
Polished;Lobster;Sterling silver;
Polished;Flat back;Engravable;Sterling silver;Fancy lobster;Heart;
Polished;Flat back;Engravable;Sterling silver;Fancy lobster;Heart;
Polished;Flat back;Engravable;Lobster;Sterling silver;Heart;
Solid;Polished;Flat back;Engravable;Lobster;Sterling silver;Heart;
Polished;Flat back;Engravable;Lobster;Sterling silver;Heart;
Polished;Lobster;Sterling silver;Beaded;
Solid;Polished;Lobster;Sterling silver;
Casted;Polished;Lobster;Sterling silver;
Polished;Lobster;Sterling silver;Heart;Love;
Casted;Lobster;Sterling silver;2" extension;14" chain;
Spring Ring;Sterling silver;
Spring Ring;Sterling silver;Twisted;
Spring Ring;Sterling silver;Twisted;
Spring Ring;Sterling silver;Twisted;
Spring Ring;Split Ring;Sterling silver;Beaded Chain;
Polished;Sterling silver;Fancy lobster;1" extender;Bead;
Polished;Sterling silver;Fancy lobster;
Polished;Sterling silver;Fancy lobster;
Polished;Sterling silver;Fancy lobster;
Polished;Sterling silver;Fancy lobster;
Polished;Lobster;Sterling silver;
Polished;Lobster;Sterling silver;
Polished;Hollow;Lobster;Sterling silver;
Polished;Lobster;Sterling silver;
Casted;Polished;Hollow;Lobster;Sterling silver;
Casted;Polished;Hollow;Lobster;Sterling silver;
Solid;Casted;Polished;Lobster;Sterling silver;Rhodium-plated;
Solid;Casted;Polished;Lobster;Sterling silver;Rhodium-plated;
Polished;Hollow;Lobster;Sterling silver;
Polished;Hollow;Lobster;Sterling silver;
Polished;Hollow;Lobster;Sterling silver;
;
Casted;Polished;Lobster;Sterling silver;
Casted;Polished;Sterling silver;Fancy lobster;
Polished;Lobster;Sterling silver;
Polished;Sterling silver;Fancy lobster;Heart;
Spring Ring;Sterling silver;
Polished;Sterling silver;Fancy lobster;Textured;
Polished;Sterling silver;Fancy lobster;
Polished;Sterling silver;Fancy lobster;
Polished;Sterling silver;Fancy lobster;
Polished;Sterling silver;Fancy lobster;
Polished;Sterling silver;Freshwater cultured pearl;Fancy lobster;Shepherd hook;
Polished;Sterling silver;Freshwater cultured pearl;Fancy lobster;Shepherd hook;
Polished;Post;Sterling silver;Freshwater cultured pearl;Fancy lobster;
Polished;Sterling silver;Fancy lobster;1.5" extension;
Diamond-cut;Polished;Spring Ring;Sterling silver;1" extender;
Polished;Sterling silver;Fancy lobster;1" extender;Diamond Cut;
Diamond-cut;Polished;Sterling silver;Fancy lobster;1" extender;
Diamond-cut;Lobster;Sterling silver;1" extender;Adjustable;
Polished;Lobster;Sterling silver;
Polished;Sterling silver;Fancy lobster;1" extender;
Polished;Sterling silver;Fancy lobster;1" extender;
Polished;Sterling silver;Fancy lobster;1" extender;
Polished;Sterling silver;Fancy lobster;1" extender;
Polished;Sterling silver;Fancy lobster;1" extender;
Spring Ring;Sterling silver;Rhodium-plated;1" extender;
Polished;Sterling silver;Fancy lobster;1" extender;Heart;
Polished;Fancy lobster;Rhodium-plated;
Polished;Sterling silver;Fancy lobster;Rhodium-plated;
Polished;Sterling silver;Fancy lobster;
Polished;Sterling silver;Fancy lobster;
Polished;Sterling silver;Fancy lobster;
Polished;Sterling silver;Fancy lobster;2" extension;
Spring Ring;Sterling silver;Rhodium-plated;1" extender;Heart;
Solid;Polished;Spring Ring;Sterling silver;Box chain;
Polished;Sterling silver;Fancy lobster;1" extender;Heart;
Sterling silver;CZ;Fancy lobster;Rhodium-plated;1" extender;
Polished;Sterling silver;Fancy lobster;1" extender;
Solid;Polished;Spring Ring;Sterling silver;Box chain;
Solid;Polished;Spring Ring;Sterling silver;
Solid;Polished;Spring Ring;Sterling silver;
Solid;Polished;Sterling silver;Fancy lobster;Not engraveable;
Simulated;Sterling silver;Fancy lobster;Shepherd hook;Beaded Chain;
Polished;Sterling silver;Fancy lobster;Shepherd hook;Dangle;Vermeil;
Polished;Lobster;Sterling silver;1" extender;
Polished;Sterling silver;Fancy lobster;Gold-plated;1" extender;
Polished;Sterling silver;Fancy lobster;1" extender;Heart;
Polished;Sterling silver;Fancy lobster;1" extender;
Polished;Sterling silver;Fancy lobster;1" extender;Heart;
Polished;Sterling silver;Fancy lobster;1" extender;Heart;Glass bead;
Polished;Sterling silver;Fancy lobster;1" extender;Flower;
Polished;Sterling silver;Fancy lobster;1" extender;
Polished;Sterling silver;Fancy lobster;1" extender;
Polished;Spring Ring;Sterling silver;1" extender;
Polished;Sterling silver;Fancy lobster;1" extender;
Polished;Sterling silver;Fancy lobster;1" extender;
Spring Ring;Sterling silver;1" extender;
Spring Ring;Sterling silver;1" extender;
Spring Ring;Sterling silver;1" extender;
Polished;Sterling silver;Fancy lobster;1" extender;
Polished;Sterling silver;Fancy lobster;1" extender;
Polished;Sterling silver;Fancy lobster;1" extender;
Polished;Flat back;Engravable;Sterling silver;Toggle;Heart;
Diamond-cut;Polished;Spring Ring;Sterling silver;
Polished;Spring Ring;Sterling silver;
Polished;Lobster;Sterling silver;
Polished;Lobster;Sterling silver;
Polished;Sterling silver;CZ;1" extender;
Polished;Sterling silver;CZ;Fancy lobster;1" extender;
Polished;Sterling silver;CZ;Fancy lobster;2" extension;
Polished;Sterling silver;CZ;Fancy lobster;2" extension;
Polished;Fold-over;Sterling silver;Adjustable;Love;Antiqued;Pink;Swarovski elements;
Polished;Fold-over;Sterling silver;Adjustable;Twisted;Blue;
Polished;Sterling silver;Adjustable;Antiqued;Purple;Swarovski elements;
Polished;Lobster;Sterling silver;1" extender;
Polished;Lobster;CZ;1" extender;Bead;
Polished;Sterling silver;Fancy lobster;1" extender;
Polished;Spring Ring;Sterling silver;CZ;
Diamond-cut;Polished;Sterling silver;Laser-cut;Dangle;Rose-tone;Rhodium-plated;Brushed;
Polished;Spring Ring;Sterling silver;Crystal;Dangle;Brushed;
Polished;Spring Ring;Sterling silver;Crystal;Dangle;Cut-out;
Polished;Sterling silver;Fancy lobster;Laser-cut;Dangle;Beaded;
Solid;Polished;Spring Ring;Sterling silver;
Polished;3-D;Stamped;Lobster;Sterling silver;
Solid;Polished;Spring Ring;Sterling silver;
Solid;Polished;Spring Ring;Sterling silver;
Solid;Polished;Spring Ring;Sterling silver;
Solid;Polished;Spring Ring;Sterling silver;
Solid;Polished;Spring Ring;Sterling silver;
Polished;Lobster;Sterling silver;
Solid;Polished;Open back;Sterling silver;Fancy lobster;
Solid;Casted;Polished;Open back;Sterling silver;Fancy lobster;
Solid;Casted;Polished;Open back;Sterling silver;Fancy lobster;
Casted;Polished;Hollow;Lobster;Sterling silver;
Polished;Lobster;Sterling silver;
Polished;Lobster;Sterling silver;
Polished;Spring Ring;Sterling silver;
Polished;Spring Ring;Sterling silver;Heart;
Post;Spring Ring;Sterling silver;Freshwater cultured pearl;Dangle;
Post;Spring Ring;Sterling silver;Freshwater cultured pearl;
Post;Spring Ring;Sterling silver;Freshwater cultured pearl;
Post;Spring Ring;Sterling silver;Freshwater cultured pearl;
Sterling silver;Freshwater cultured pearl;Fancy lobster;Shepherd hook;
Post;Spring Ring;Sterling silver;Freshwater cultured pearl;
Post;Spring Ring;Sterling silver;Freshwater cultured pearl;Dangle;
Post;Spring Ring;Sterling silver;Freshwater cultured pearl;Dangle;
Post;Spring Ring;Sterling silver;Freshwater cultured pearl;
Post;Spring Ring;Sterling silver;Freshwater cultured pearl;
Freshwater cultured pearl;White;Stretch;
Post;Spring Ring;Sterling silver;Freshwater cultured pearl;Stretch;
Post;Spring Ring;Sterling silver;Freshwater cultured pearl;Stretch;
Post;Sterling silver;Freshwater cultured pearl;Stretch;
Post;Spring Ring;Sterling silver;Freshwater cultured pearl;Stretch;
Post;Spring Ring;Sterling silver;Freshwater cultured pearl;
Post;Sterling silver;Freshwater cultured pearl;
Post;Sterling silver;Freshwater cultured pearl;Stretch;
Post;Sterling silver;Freshwater cultured pearl;White;
Post;Sterling silver;Freshwater cultured pearl;Stretch;
Post;Sterling silver;Freshwater cultured pearl;Stretch;
Crystal;Pink;Shell pearl;Stretch;
Crystal;Pink;Purple;Shell pearl;Stretch;
Polished;Post;Sterling silver;Freshwater cultured pearl;Fancy lobster;
Polished;Post;Sterling silver;Freshwater cultured pearl;Fancy lobster;
Polished;Spring Ring;Sterling silver;Freshwater cultured pearl;2" extension;
Polished;Post;Sterling silver;Freshwater cultured pearl;Fancy lobster;
Polished;Lobster;Sterling silver;Freshwater cultured pearl;Dangle;Removeable;
Polished;Post;Lobster;Sterling silver;Freshwater cultured pearl;
Polished;Post;Lobster;Sterling silver;Freshwater cultured pearl;CZ;
Polished;Post;Lobster;Sterling silver;Freshwater cultured pearl;CZ;
Polished;Post;Lobster;Sterling silver;Freshwater cultured pearl;
Polished;Post;Lobster;Sterling silver;Freshwater cultured pearl;CZ;
Box;Sterling silver;Freshwater cultured pearl;Onyx;Shepherd hook;Stretch;
Sterling silver;Freshwater cultured pearl;Crystal;Shepherd hook;Gift Boxed;Stretch;
Freshwater cultured pearl;Stretch;Set of 5;
Post;Spring Ring;Sterling silver;Freshwater cultured pearl;Gift Boxed;Set of two;
Polished;Freshwater cultured pearl;Hematite;Stretch;
Polished;Post;Enamel;Sterling silver;Set of 3;
Polished;Spring Ring;Sterling silver;Freshwater cultured pearl;
Diamond-cut;Polished;Spring Ring;Sterling silver;Cable chain;
Diamond-cut;Polished;Spring Ring;Sterling silver;Cable chain;
Spring Ring;Sterling silver;Box chain;Half Round;
Polished;Engravable;Lobster;Sterling silver;
Polished;Engravable;Lobster;Sterling silver;
Polished;Engravable;Spring Ring;Sterling silver;Adjustable;
Polished;Engravable;Lobster;Sterling silver;Heart;
Casted;Polished;Lobster;Sterling silver;Not engraveable by QG;
Casted;Polished;Engravable;Lobster;Sterling silver;
Casted;Polished;Engravable;Lobster;Sterling silver;
Casted;Polished;Engravable;Lobster;Sterling silver;
Casted;Polished;Engravable;Spring Ring;Sterling silver;
Casted;Polished;Engravable;Spring Ring;Sterling silver;
Casted;Polished;Engravable;Lobster;Sterling silver;
Solid;Polished;Engravable;Lobster;Sterling silver;
Casted;Polished;Engravable;Lobster;Sterling silver;Adjustable;
Casted;Polished;Engravable;Spring Ring;Sterling silver;
Polished;Hollow;Spring Ring;Sterling silver;
Polished;Hollow;Spring Ring;Sterling silver;
Polished;Hollow;Spring Ring;Sterling silver;
Polished;Hollow;Spring Ring;Sterling silver;
Polished;Hollow;Lobster;
Polished;Hollow;Lobster;
Polished;Hollow;Lobster;Sterling silver;Beaded;
Polished;Sterling silver;Fancy lobster;Rhodium-plated;
Polished;Sterling silver;Fancy lobster;1" extender;
Solid;Polished;Lobster;Sterling silver;Open;
Polished;Sterling silver;Not engraveable by QG;26mm;Holds 2 photos;
Polished;Sterling silver;Not engraveable by QG;Textured;15mm;Holds 2 photos;
Polished;Sterling silver;Not engraveable by QG;20mm;Holds 2 photos;
Polished;Flat back;Sterling silver;Not engraveable by QG;Patterned;Holds 2 photos;
Polished;Sterling silver;Diamond;Not engraveable by QG;18" chain;Rose gold-plated;14" chain;20mm;
Polished;Engravable;Sterling silver;Fits up to 3mm;
Polished;Engravable;Sterling silver;Fits up to 3mm;
Polished;Engravable;Sterling silver;Fits up to 3mm;
Polished;Engravable;Sterling silver;Fits up to 3mm;
Polished;Engravable;Sterling silver;Fits up to 3mm;
Polished;Engravable;Sterling silver;Fits up to 3mm;
Polished;Engravable;Sterling silver;Fits up to 3mm;
Polished;Engravable;Sterling silver;Fits up to 3mm;
Polished;Engravable;Sterling silver;Fits up to 3mm;
Polished;Engravable;Sterling silver;Fits up to 3mm;
Polished;Engravable;Sterling silver;Fits up to 3mm;
Polished;Engravable;Sterling silver;Fits up to 3mm;
Polished;Engravable;Sterling silver;Fits up to 3mm;
Polished;Engravable;Sterling silver;Fits up to 3mm;
Polished;Engravable;Sterling silver;Patterned;Fits up to 3mm;
Polished;Engravable;Sterling silver;Diamond Cut;Fits up to 3mm;
Polished;Engravable;Sterling silver;Diamond Cut;Fits up to 3mm;
Polished;Engravable;Sterling silver;
Polished;Engravable;Sterling silver;
Polished;Engravable;Sterling silver;
Polished;Engravable;Sterling silver;
Polished;Engravable;Sterling silver;
Polished;Engravable;Sterling silver;
Polished;Engravable;Sterling silver;
Polished;Engravable;Sterling silver;
Polished;Engravable;Sterling silver;
Polished;Engravable;Sterling silver;Fits up to 3mm;
Polished;Engravable;Sterling silver;Fits up to 3mm;
Polished;Post;Spring Ring;Sterling silver;CZ;Dangle;White;Shell pearl;
Post;Lobster;Spring Ring;Sterling silver;CZ;Dangle;White;Shell pearl;
Spring Ring;Sterling silver;CZ;Shepherd hook;Dangle;White;Shell pearl;
Polished;Post;Spring Ring;Sterling silver;CZ;Dangle;White;Shell pearl;
Polished;Post;Spring Ring;Sterling silver;CZ;Dangle;White;Shell pearl;
Polished;Post;Spring Ring;Sterling silver;CZ;Dangle;White;Shell pearl;
Hinged;Spring Ring;Sterling silver;CZ;Dangle;Black;Shell pearl;
Polished;Post;Spring Ring;Sterling silver;CZ;Dangle;White;Shell pearl;
Polished;Sterling silver;CZ;Pave;33stones;Set of two;
Sterling silver;CZ;Rhodium-plated;Pave;33stones;Set of two;
Sterling silver;CZ;Rhodium-plated;Pave;214 stones;Set of 3;
Sterling silver;CZ;Rhodium-plated;Pave;214 stones;
Sterling silver;CZ;Rhodium-plated;Pave;214 stones;
Lobster;Sterling silver;CZ;Rhodium-plated;2" extension;18" chain;Pave;26 stones;Cable chain;
Sterling silver;CZ;Rhodium-plated;Pave;216 stones;Set of four;
Sterling silver;CZ;Rhodium-plated;Pave;216 stones;
Sterling silver;CZ;Rhodium-plated;Pave;216 stones;
Solid;Polished;Sterling silver;
Polished;Sterling silver;CZ;Rhodium-plated;
Antique finish;Sterling silver;Marcasite;Flower;
Antique finish;Sterling silver;Marcasite;
Antique finish;Sterling silver;Freshwater cultured pearl;Marcasite;Mother of pearl;Agate;Black;
Antique finish;Sterling silver;Marcasite;
Antique finish;Sterling silver;Marcasite;Mother of pearl;Crystal;Swarovski Elements;
Polished;Enamel;Antique finish;Sterling silver;Marcasite;White topaz;
Polished;Sterling silver;
Polished;Open back;Sterling silver;Rhodolite garnet;Rhodium-plated;Chrome diopside;
Polished;Sterling silver;Freshwater cultured pearl;CZ;
Polished;Sterling silver;Freshwater cultured pearl;CZ;
Polished;Sterling silver;Freshwater cultured pearl;CZ;
Polished;Sterling silver;Freshwater cultured pearl;CZ;
Polished;Sterling silver;Freshwater cultured pearl;CZ;
Polished;Spring Ring;Sterling silver;
Polished;Spring Ring;Sterling silver;
Polished;Spring Ring;Sterling silver;
Polished;Spring Ring;Sterling silver;
Polished;Spring Ring;Sterling silver;
Polished;Lobster;Sterling silver;Beveled Edge;
Polished;Spring Ring;Sterling silver;
Polished;Lobster;Sterling silver;Box chain;Twisted;
Polished;Lobster;Sterling silver;Box chain;Twisted;
Solid;Polished;Lobster;Sterling silver;
Solid;Polished;Lobster;Sterling silver;
Spring Ring;Sterling silver;Rhodium-plated;2" extension;
Solid;Polished;Lobster;Sterling silver;
Solid;Polished;Spring Ring;Sterling silver;
Polished;Lobster;Sterling silver;
Polished;Lobster;Sterling silver;
Polished;Lobster;Sterling silver;
Polished;Lobster;Sterling silver;
Polished;Spring Ring;Sterling silver;
Solid;Polished;Spring Ring;Sterling silver;
Polished;Spring Ring;Sterling silver;
Sterling silver;Rhodium-plated;
Polished;Spring Ring;Sterling silver;
Polished;Spring Ring;Sterling silver;
Polished;Spring Ring;Sterling silver;
Diamond-cut;Polished;Spring Ring;Sterling silver;
Diamond-cut;Polished;Spring Ring;Sterling silver;
Diamond-cut;Polished;Spring Ring;Sterling silver;
Polished;Lobster;Sterling silver;
Solid;Polished;Lobster;Sterling silver;
Solid;Polished;Lobster;Sterling silver;
Solid;Polished;Lobster;Sterling silver;
Solid;Polished;Lobster;Sterling silver;
Solid;Polished;Lobster;Sterling silver;
Solid;Polished;Spring Ring;Sterling silver;
Spring Ring;Sterling silver;Flat;Cable chain;
Spring Ring;Sterling silver;Flat;Cable chain;
Spring Ring;Sterling silver;Rhodium;
Diamond-cut;Spring Ring;Sterling silver;Cable chain;
Diamond-cut;Spring Ring;Sterling silver;Cable chain;
Spring Ring;Sterling silver;Round;
Solid;Polished;Sterling silver;Textured;
Solid;Polished;Sterling silver;
Solid;Polished;Sterling silver;Textured;
Solid;Polished;Sterling silver;Textured;
Solid;Polished;Flat back;Engravable;Sterling silver;
Solid;Polished;Flat back;Engravable;Sterling silver;
Solid;Polished;Engravable;Sterling silver;
Solid;Polished;Engravable;Sterling silver;Textured back;
Solid;Polished;Sterling silver;
Solid;Polished;Engravable;SS & vermeil;
Solid;Polished;Sterling silver;Not engraveable;
Solid;Polished;Flat back;Engravable;Sterling silver;
Solid;Polished;Engravable;Sterling silver;Textured;
Solid;Polished;Engravable;Sterling silver;
Solid;Sterling silver;Not engraveable;Textured back;
Solid;Polished;Engravable;Enamel;Sterling silver;
Solid;Diamond-cut;Polished;Engravable;Sterling silver;
Solid;Polished;Engravable;Sterling silver;
Solid;Polished;Engravable;Sterling silver;
Solid;Polished;Engravable;Sterling silver;
Solid;Polished;Engravable;Sterling silver;
Solid;Engravable;Sterling silver;Polished & satin;
Solid;Polished;Engravable;Sterling silver;
Solid;Polished;Engravable;Sterling silver;
Solid;Polished;Engravable;Sterling silver;
Solid;Polished;Engravable;Enamel;Sterling silver;
Solid;Polished;Engravable;Enamel;Sterling silver;
Solid;Polished;Engravable;Sterling silver;
Solid;Polished;Engravable;Sterling silver;Textured;
Solid;Diamond-cut;Engravable;Sterling silver;Polished & satin;
Solid;Diamond-cut;Polished;Engravable;Sterling silver;
Solid;Polished;Sterling silver;Rhodium-plated;
Solid;Polished;Sterling silver;Rhodium-plated;
Solid;Casted;Polished;Sterling silver;
Solid;Casted;Polished;Sterling silver;
Solid;Casted;Polished;Sterling silver;
Solid;Polished;Sterling silver;Antiqued;Blue;Stellux crystal;
Solid;Polished;Sterling silver;Antiqued;
Solid;Polished;Sterling silver;
Solid;Polished;Sterling silver;
Solid;Polished;Sterling silver;
Solid;Polished;Sterling silver;Stellux crystal;
Solid;Casted;Polished;Antique finish;Sterling silver;
Solid;Casted;Polished;Antique finish;Sterling silver;
Casted;Polished;Open back;Sterling silver;CZ;Rhodium-plated;
Solid;Polished;Closed back;Engravable;Sterling silver;
Polished;Sterling silver;
;
Polished;Sterling silver;CZ;
Polished;Sterling silver;CZ;
Solid;Polished;Sterling silver;
Solid;Polished;Sterling silver;
Solid;Casted;Polished;Enamel;Sterling silver;CZ;Solid Back;Set of 3;
Solid;Casted;Polished;Enamel;Sterling silver;CZ;Solid Back;Set of 3;
Solid;Casted;Polished;Enamel;Sterling silver;CZ;Solid Back;Set of 3;
;
;
Solid;Casted;Polished;Sterling silver;
Polished;Open back;Sterling silver;CZ;Set of 3;
Polished;Open back;Sterling silver;CZ;Set of 3;
Polished;Open back;Sterling silver;CZ;Set of 3;
Solid;Polished;Sterling silver;CZ;Set of 3;
Solid;Polished;Sterling silver;CZ;Set of 3;
Solid;Casted;Sterling silver;Textured;
Solid;Polished;Sterling silver;CZ;Solid Back;
Solid;Polished;Sterling silver;CZ;Solid Back;
Solid;Casted;Sterling silver;
Solid;Casted;Sterling silver;
Solid;Casted;Polished;Sterling silver;Textured;
Solid;Casted;Sterling silver;Textured;
Polished;Sterling silver;CZ;Textured;Solid Back;Pink CZ;Blue CZ;
Solid;Casted;Sterling silver;Textured;
Solid;Casted;Sterling silver;
Solid;Casted;Polished;Enamel;Sterling silver;
Solid;Casted;Sterling silver;
Solid;Casted;Antique finish;Sterling silver;Rhodium-plated;
Solid;Casted;Antique finish;Sterling silver;
Solid;Casted;Sterling silver;
Solid;Casted;Sterling silver;Heart;
Solid;Casted;Antique finish;Sterling silver;
Solid;Casted;Antique finish;Sterling silver;
Solid;Casted;Sterling silver;Cut-out;
Solid;Casted;Sterling silver;
Solid;Casted;Antique finish;Sterling silver;
Solid;Casted;Sterling silver;
Solid;Casted;Sterling silver;CZ;Antiqued;
Solid;Casted;Sterling silver;
Solid;Casted;Sterling silver;
Solid;Casted;Antique finish;Sterling silver;
Solid;Casted;Polished;Sterling silver;
Solid;Casted;Polished;Sterling silver;
Solid;Casted;Polished;Sterling silver;
Solid;Casted;Polished;Sterling silver;
Solid;Casted;Polished;Sterling silver;
Solid;Casted;Polished;Antique finish;Sterling silver;
Solid;Casted;Polished;Antique finish;Sterling silver;
Solid;Casted;Polished;Antique finish;Sterling silver;
Solid;Polished;Lobster;Sterling silver;Round;
Solid;Polished;Lobster;Sterling silver;Round;
Lobster;Sterling silver;Leather;Black;
Lobster;Sterling silver;Leather;Black;
Lobster;Sterling silver;Leather;Black;
Lobster;Sterling silver;Leather;Black;
Lobster;Sterling silver;Leather;Black;
Lobster;Sterling silver;
Lobster;Sterling silver;
Lobster;Sterling silver;
Sterling silver;Fancy lobster;
Lobster;Sterling silver;
Lobster;Sterling silver;
Lobster;Sterling silver;
Lobster;Sterling silver;
Lobster;Sterling silver;
Lobster;Sterling silver;
Hinged;Sterling silver;
Hinged;Sterling silver;
Hinged;Sterling silver;
Hinged;Sterling silver;
Hinged;Sterling silver;
Hinged;Sterling silver;
Polished;Hinged;
Polished;Sterling silver;Rhodium-plated;Heart;Patterned;
Polished;Sterling silver;Rhodium-plated;Heart;Patterned;
Polished;Sterling silver;Rhodium-plated;Heart;Patterned;
Polished;Sterling silver;Rhodium-plated;Heart;Patterned;
Polished;Sterling silver;Rhodium-plated;Twisted;
Polished;Sterling silver;Rhodium-plated;
Polished;Sterling silver;Rhodium-plated;
Polished;Sterling silver;Rhodium-plated;
Polished;Sterling silver;Rhodium-plated;
Polished;Sterling silver;Rhodium-plated;
Polished;Sterling silver;Rhodium-plated;
Polished;Sterling silver;Rhodium-plated;
Polished;Sterling silver;18k gold-plate pink color;
Polished;Sterling silver;Rhodium-plated;Patterned;
Polished;Sterling silver;Rhodium-plated;Patterned;
Polished;Sterling silver;Rhodium-plated;Patterned;
Polished;Sterling silver;Rhodium-plated;Patterned;
Polished;Sterling silver;Rhodium-plated;
Polished;Sterling silver;Diamond;Prong set;Rhodium-plated;Patterned;
Polished;Sterling silver;Amethyst;Prong set;Rhodium-plated;Patterned;
Polished;Sterling silver;Prong set;Round;Rhodium-plated;Patterned;Created Sapphire;
Polished;Sterling silver;Diamond;Prong set;Round;Rhodium-plated;Created Sapphire;
Polished;Antique finish;Sterling silver;Patterned;
Polished;Antique finish;Sterling silver;Patterned;
Polished;Spring Ring;Sterling silver;
Polished;Spring Ring;Sterling silver;Round;Snake Chain;
Polished;Spring Ring;Sterling silver;Round;Snake Chain;
Polished;Spring Ring;Sterling silver;Round;Snake Chain;
Solid;Polished;Lobster;Sterling silver;Round;Snake Chain;
Solid;Polished;Lobster;Sterling silver;Round;Snake Chain;
Solid;Polished;Lobster;Sterling silver;Round;Snake Chain;
Lobster;Sterling silver;Rhodium-plated;2" extension;Snake Chain;
Solid;Polished;Lobster;Sterling silver;Round;Snake Chain;
Solid;Polished;Lobster;Sterling silver;Round;Snake Chain;
Solid;Polished;Lobster;Sterling silver;Round;Snake Chain;
Solid;Polished;Lobster;Sterling silver;Round;Snake Chain;
Solid;Polished;Lobster;Sterling silver;Round;Snake Chain;
Polished;Spring Ring;Sterling silver;Round;Snake Chain;
Polished;Lobster;Sterling silver;Round;Snake Chain;
Solid;Polished;Spring Ring;Sterling silver;Round;
Solid;Polished;Spring Ring;Sterling silver;Round;
Solid;Polished;Spring Ring;Sterling silver;Round;
Solid;Polished;Spring Ring;Sterling silver;Round;
Solid;Polished;Lobster;Sterling silver;Round;
Solid;Polished;Lobster;Sterling silver;Round;
Solid;Polished;Lobster;Sterling silver;Round;
Solid;Polished;Lobster;Sterling silver;Round;
Solid;Polished;Lobster;Sterling silver;Round;
Solid;Polished;Lobster;Sterling silver;Round;
Solid;Polished;Lobster;Sterling silver;Round;
Solid;Polished;Lobster;Sterling silver;Round;
Solid;Polished;Lobster;Sterling silver;Round;
Diamond-cut;Spring Ring;Sterling silver;Round;
Diamond-cut;Spring Ring;Sterling silver;Round;
Solid;Casted;Antique finish;Lobster;Sterling silver;Shepherd hook;
;
Polished;Post;Sterling silver;CZ;
Polished;Post;Sterling silver;CZ;
Polished;Post;Sterling silver;CZ;
Polished;Post;Sterling silver;CZ;
Polished;Post;Antique finish;Sterling silver;CZ;
Polished;Post;Sterling silver;CZ;Rhodium-plated;
Polished;Post;Sterling silver;CZ;
Polished;Post;Sterling silver;CZ;
Polished;Post;Sterling silver;CZ;
Polished;Post;Sterling silver;CZ;
Polished;Post;Sterling silver;CZ;Rhodium-plated;
Polished;Post;Sterling silver;CZ;Chain slide;Hidden bail;
Polished;Post;Sterling silver;CZ;
Polished;Post;Sterling silver;CZ;Prong set;Rhodium-plated;Chain slide;Hidden bail;
Polished;Post;Sterling silver;CZ;Rhodium-plated;
Polished;Post;Sterling silver;CZ;
Polished;Open back;Post;Sterling silver;CZ;Rhodium-plated;Fits up to 2mm;
Polished;Post;Sterling silver;CZ;Prong set;Dangle;Rhodium-plated;Hidden bail;Fits up to 2mm;
Polished;Sterling silver;CZ;Prong set;Shepherd hook;Dangle;Rhodium-plated;Hidden bail;Fits up to 2mm;
Polished;Sterling silver;CZ;Shepherd hook;
Polished;Post;Sterling silver;CZ;Created opal;Rhodium-plated;
Polished;Post;Sterling silver;Created opal;Rhodium-plated;
Polished;Post;Sterling silver;Created opal;Rhodium-plated;
Polished;Post;Sterling silver;CZ;
Polished;Post;Sterling silver;CZ;Dangle;
Casted;Polished;Post;Sterling silver;CZ;Rhodium-plated;
Polished;Sterling silver;Filigree;Shepherd hook;Dangle;
Casted;Polished;Post;Sterling silver;CZ;Rhodium-plated;
Polished;Post;Gold-plated;
Polished;Spring Ring;Sterling silver;Pink CZ;
Casted;Polished;Post;Sterling silver;CZ;Rhodium-plated;
Polished;Post;Sterling silver;CZ;Chain slide;
Polished;Post;Sterling silver;Green agate;Dangle;
Polished;Post;Sterling silver;Blue topaz;Fits up to 3mm;
Polished;Post;Sterling silver;Dangle;
Polished;Post;Sterling silver;Dangle;
Polished;Post;Sterling silver;Dangle;
Polished;Sterling silver;Shepherd hook;Dangle;
Polished;Sterling silver;Shepherd hook;Dangle;
Polished;Post;Sterling silver;Dangle;
Casted;Polished;Post;Sterling silver;CZ;Rhodium-plated;
Casted;Polished;Sterling silver;CZ;Shepherd hook;Rhodium-plated;
Casted;Polished;Sterling silver;CZ;Shepherd hook;Rhodium-plated;
Casted;Polished;Sterling silver;CZ;Shepherd hook;Rhodium-plated;
Casted;Polished;Sterling silver;CZ;Shepherd hook;Rhodium-plated;
Polished;Hollow;Lobster;Sterling silver;CZ;2" extension;
Casted;Polished;Post;Sterling silver;CZ;Crystal;Rhodium-plated;Chain slide;Hidden bail;
Casted;Polished;Open back;Post;Sterling silver;CZ;Prong set;Rhodium-plated;Hidden bail;Fits up to 2mm;
Casted;Polished;Post;Sterling silver;CZ;Rhodium-plated;Chain slide;Hidden bail;
Casted;Polished;Post;Sterling silver;CZ;Rhodium-plated;
Polished;Antique finish;Polished back;Spring Ring;Sterling silver;Rhodium-plated;18" chain;Opens;Gift pouch;
Solid;Polished;Engravable;Sterling silver;Lightweight;Flat Band;
Solid;Polished;Stamped;Engravable;Sterling silver;Half Round;
Solid;Polished;Stamped;Engravable;Sterling silver;Half Round;
Solid;Polished;Stamped;Engravable;Sterling silver;Half Round;
Solid;Polished;Stamped;Engravable;Sterling silver;Half Round;
Solid;Polished;Stamped;Engravable;Sterling silver;Half Round;
Solid;Polished;Stamped;Engravable;Sterling silver;Half Round;
Solid;Polished;Stamped;Engravable;Sterling silver;Half Round;
Solid;Polished;Stamped;Engravable;Sterling silver;Half Round;
Solid;Polished;Stamped;Engravable;Sterling silver;Half Round;
Solid;Polished;Stamped;Engravable;Sterling silver;Half Round;
Solid;Polished;Engravable;Sterling silver;Half Round;
Solid;Polished;Engravable;Sterling silver;Half Round;
Solid;Polished;Engravable;Sterling silver;Half Round;
Solid;Polished;Engravable;Sterling silver;Half Round;
Solid;Polished;Engravable;Sterling silver;Half Round;
Solid;Polished;Engravable;Sterling silver;Half Round;
Solid;Polished;Engravable;Sterling silver;Half Round;
Solid;Polished;Engravable;Sterling silver;Half Round;
Solid;Polished;Engravable;Sterling silver;Half Round;
Solid;Polished;Engravable;Sterling silver;Half Round;
Solid;Polished;Engravable;Sterling silver;Half Round;
Polished;Sterling silver;Diamond;Box catch;Created opal;Rhodium-plated;
Solid;Polished;Engravable;Sterling silver;Laser Etched;
Solid;Polished;Engravable;Sterling silver;Laser Etched;
Solid;Polished;
Solid;Polished;14k Yellow gold;Textured;
Solid;Diamond-cut;Polished;14K White gold;
Solid;Lobster;14k Rose gold;
Solid;Diamond-cut;Spring Ring;14k Rose gold;
Polished;14k Yellow gold;Hollow;Leverback;
14k Yellow gold;Post;Spring Ring;Freshwater cultured pearl;Screw back;
Polished;14k Yellow gold;Hollow;Hinged post;
Polished;14k Yellow gold;Hollow;Endless hoop;
Polished;Post;14k Rose gold;
Polished;14K White gold;Hollow;Endless hoop;
Polished;14K White gold;Hollow;Post;Screw back;
Polished;14k Yellow gold;Post;Spring Ring;Freshwater cultured pearl;Set of 3;
Polished;14K Two-tone;Hollow;Post;Reversible;Screw back;
Polished;14k Yellow gold;Hollow;Post;Reversible;Screw back;
Polished;14k Yellow gold;Hollow;Post;Screw back;
Polished;14k Yellow gold;Hollow;Post;Reversible;Freshwater cultured pearl;Screw back;
Polished;14k Yellow gold;Hollow;Post;Reversible;Prong set;Crystal;Screw back;
Polished;14k Yellow gold;Hollow;Post;Reversible;CZ;Prong set;Screw back;
Polished;14K White gold;
Polished;14k Yellow gold;
Polished;14k Yellow gold;Engravable;Fancy lobster;
Diamond-cut;Polished;14K Two-tone;Leverback;
Polished;Engravable;Stainless Steel;Brushed;Beveled Edge;Flat Band;
Polished;Engravable;Stainless Steel;Brushed;Beveled Edge;Flat Band;
Polished;Engravable;Stainless Steel;Half Round;
Polished;Engravable;Stainless Steel;Half Round;
Polished;Engravable;Stainless Steel;Half Round;
Polished;Engravable;Stainless Steel;Half Round;
Polished;Engravable;Stainless Steel;Half Round;
Polished;Engravable;Stainless Steel;Half Round;
Polished;Engravable;Stainless Steel;Half Round;
Polished;Engravable;Stainless Steel;Half Round;
Polished;Engravable;Stainless Steel;Brushed;Ridged edge;
Polished;Engravable;Stainless Steel;Brushed;Ridged edge;
Polished;Engravable;Stainless Steel;Brushed;Ridged edge;
Polished;Engravable;Stainless Steel;Brushed;Ridged edge;
Polished;Engravable;Stainless Steel;Brushed;Ridged edge;
Polished;Engravable;Stainless Steel;Black Carbon Fiber;
Polished;Engravable;Stainless Steel;Black Carbon Fiber;
Polished;Engravable;Stainless Steel;Black Carbon Fiber;
Engravable;Stainless Steel;Rubber;Brushed;
Polished;Stainless Steel;
Polished;Stainless Steel;
Polished;Stainless Steel;
Polished;Stainless Steel;
Polished;Engravable;Stainless Steel;Brushed;Ridged edge;
Polished;Fancy lobster;Stainless Steel;
Polished;Fancy lobster;Stainless Steel;
Polished;Spring Ring;Stainless Steel;1" extender;
Polished;Spring Ring;Stainless Steel;1" extender;
Polished;Spring Ring;Stainless Steel;1" extender;
Polished;Spring Ring;Stainless Steel;
Polished;Spring Ring;Stainless Steel;1" extender;
Polished;Fancy lobster;Stainless Steel;
Fold-over;Stainless Steel;Brushed;
Polished;CZ;Stainless Steel;
Polished;Stainless Steel;
Polished;Barrel;Leather;Stainless Steel;Metal;Brown;Black rubber;
Polished;Fold-over;Stainless Steel;IPB Black-plated;
Polished;Fancy lobster;Stainless Steel;
Polished;Leather;Stainless Steel;Magnetic Clasp;IP black-plated;Black;
Polished;Leather;Stainless Steel;Magnetic Clasp;Brown;
Polished;Barrel;Leather;Stainless Steel;Brushed;Brown;Black rubber;
Polished;Stainless Steel;Deployment buckle;Brushed;
Polished;Leather;Stainless Steel;Magnetic Clasp;Brown;
Polished;Leather;Stainless Steel;Magnetic Clasp;Black;Woven;
Polished;Barrel;Leather;Stainless Steel;Antiqued;Black;
Polished;Barrel;Leather;Stainless Steel;Antiqued;Black;Black rubber;
Polished;Fancy lobster;Stainless Steel;
Polished;Fancy lobster;Stainless Steel;Rose IP-plated;
Polished;Stainless Steel;Deployment buckle;Black Carbon Fiber;Red;Black rubber;
Polished;Fold-over;Stainless Steel;Rose IP-plated;
Polished;Safety clasp;Stainless Steel;Black rubber;
Polished;Fold-over;Stainless Steel;
Polished;Engravable;Fancy lobster;Stainless Steel;
Polished;Fold-over;Stainless Steel;Rubber;Blue;Black rubber;
Polished;Fold-over;Leather;Stainless Steel;Brushed;IP black-plated;Black;
Polished;Fold-over;Lapis;Stainless Steel;
Polished;Engravable;Leather;Stainless Steel;Deployment buckle;Black;
Polished;Fold-over;Stainless Steel;
Polished;Engravable;Fold-over;Stainless Steel;
Engravable;Cuff;Stainless Steel;Brushed;
Polished;Fold-over;Stainless Steel;Brushed;Black Carbon Fiber;Brown IP-plated;
Polished;Hidden catch;Stainless Steel;Yellow IP-plated;
Polished;Engravable;Enamel;Fold-over;Stainless Steel;Rubber;
Polished;Engravable;Enamel;Fancy lobster;Stainless Steel;
Polished;Engravable;Enamel;Lobster;Stainless Steel;
Polished;Fancy lobster;Stainless Steel;
Polished;Fancy lobster;Stainless Steel;
Polished;Hinged;Stainless Steel;Antiqued;
Polished;Slip on;Stainless Steel;
Polished;Cuff;Stainless Steel;Cut-out;
Polished;Cuff;Stainless Steel;Cut-out;
Polished;Fancy lobster;Leather;Stainless Steel;
Polished;Leather;Stainless Steel;Magnetic Clasp;Brown;
Fold-over;Leather;Stainless Steel;Brushed;Black;
Polished;Engravable;Fancy lobster;Stainless Steel;Heart;Two piece;
Polished;Engravable;Enamel;Fancy lobster;Stainless Steel;
Polished;Fold-over;Leather;Stainless Steel;
Polished;Fancy lobster;Leather;Stainless Steel;
Polished;Fold-over;Leather;Stainless Steel;Brown;
Polished;Barrel;Leather;Stainless Steel;Antiqued;
Polished;Stainless Steel;Wood;Fleur De Lis;
Polished;Engravable;Stainless Steel;
Polished;Mother of pearl;Stainless Steel;
Polished;Engravable;Enamel;Stainless Steel;Brushed;
Polished;Stainless Steel;Wood;
Polished;Enamel;CZ;Stainless Steel;
Polished;Hematite;Stainless Steel;
Polished;Engravable;Stainless Steel;Wood;
Polished;Enamel;Stainless Steel;
Polished;Enamel;CZ;Stainless Steel;
Polished;Onyx;Mother of pearl;Stainless Steel;
Polished;Stainless Steel;Blue carbon fiber;
Polished;Engravable;Stainless Steel;
Polished;Engravable;Stainless Steel;
Polished;Engravable;Stainless Steel;Faux leather;
Polished;Hinged;Stainless Steel;
Polished;Hinged;Stainless Steel;
Polished;Hinged;Stainless Steel;
Polished;Hinged;Stainless Steel;Tapered;
Polished;Hinged;Stainless Steel;
Polished;Hinged;Stainless Steel;
Polished;Engravable;Shepherd hook;Stainless Steel;Dangle;Heart;
Polished;Hinged;Stainless Steel;
Polished;Hinged;Stainless Steel;Tapered;
Polished;Stainless Steel;IP black-plated;Hinged hoop;Tapered;
Polished;Textured;Stainless Steel;
Polished;Stainless Steel;Hinged hoop;
Polished;Stainless Steel;Cut-out;
Polished;Textured;Stainless Steel;
Polished;Shepherd hook;Stainless Steel;
Polished;Engravable;Stainless Steel;Brushed;Black Carbon Fiber;
Polished;Engravable;Stainless Steel;Brushed;Grey Carbon Fiber;
Polished;Engravable;Stainless Steel;Brushed;IP black-plated;
Polished;Engravable;Stainless Steel;Brushed;
Stainless Steel;Brushed;
Engravable;Stainless Steel;Brushed;
Engravable;Stainless Steel;Brushed;
Enamel;Engravable (front only);Stainless Steel;Brushed;
Engravable;Stainless Steel;Brushed;IP black-plated;
Polished;Engravable;Stainless Steel;Yellow IP-plated;
Polished;Engravable;Stainless Steel;IP black-plated;
Engravable;Stainless Steel;Brushed;
Polished;Engravable;Stainless Steel;Brushed;
Polished;Engravable;Stainless Steel;Brushed;Yellow IP-plated;
Polished;Engravable;Stainless Steel;Brushed;IP black-plated;
Hinged;Engravable;Diamond;Stainless Steel;Brushed;
Hinged;Engravable;Stainless Steel;Brushed;Yellow IP-plated;
Polished;Engravable;Stainless Steel;Brushed;Yellow IP-plated;
Engravable;Stainless Steel;Brushed;Black Carbon Fiber;
Polished;Engravable;Stainless Steel;Brushed;
Polished;Engravable;Stainless Steel;Brushed;
Polished;Engravable;Stainless Steel;Brushed;Yellow IP-plated;
Polished;Engravable;Stainless Steel;
Polished;Engravable;Stainless Steel;
Polished;Engravable;Stainless Steel;
Polished;Stainless Steel;Black Carbon Fiber;Grey Carbon Fiber;
Engravable;Stainless Steel;Rubber;Brushed;
Engravable;Textured;Stainless Steel;Brushed;
Polished;Engravable;Stainless Steel;Brushed;
Polished;Engravable;CZ;Stainless Steel;Rubber;
Engravable;Stainless Steel;Brushed;
Engravable;Stainless Steel;Brushed;Genuine stingray;
Polished;Stainless Steel;IP black-plated;Yellow IP-plated;
Polished;Stainless Steel;Brushed;IP black-plated;
Polished;Stainless Steel;Black Carbon Fiber;Grey Carbon Fiber;
Polished;Stainless Steel;Wood;
Polished;Stainless Steel;Carbon fiber;
Polished;Engravable;CZ;Stainless Steel;Brushed;IP black-plated;
Polished;CZ;Stainless Steel;IP black-plated;
Polished;Enamel;Stainless Steel;
Polished;Stainless Steel;Black Carbon Fiber;
Polished;Engravable;Stainless Steel;Black Carbon Fiber;
Polished;Engravable;Stainless Steel;
Polished;Engravable;CZ;Stainless Steel;Brushed;
Polished;Lapis;Stainless Steel;Brushed;
Polished;Fancy lobster;Stainless Steel;Brushed;
Polished;Fancy lobster;Stainless Steel;Black Carbon Fiber;
Polished;Fancy lobster;Stainless Steel;
Polished;Fancy lobster;Stainless Steel;
Polished;Fancy lobster;Stainless Steel;Grey Carbon Fiber;20" Chain;
Polished;Fancy lobster;Stainless Steel;Rubber;Green;
Polished;Fancy lobster;Stainless Steel;Rubber;Brown;
Polished;Fancy lobster;Stainless Steel;Rubber;Brown;
Polished;Fancy lobster;Stainless Steel;
Polished;Fancy lobster;Stainless Steel;
Polished;Fancy lobster;Stainless Steel;
Polished;Fancy lobster;Stainless Steel;
Polished;Fancy lobster;Stainless Steel;
Polished;Fancy lobster;Stainless Steel;
Polished;Fancy lobster;Stainless Steel;Cable chain;
Polished;Fancy lobster;Stainless Steel;Cable chain;
Polished;CZ;Fancy lobster;Stainless Steel;Moveable;Brushed;Black Carbon Fiber;Grey Carbon Fiber;
Polished;Fancy lobster;Stainless Steel;Brushed;
Polished;Fancy lobster;Stainless Steel;
Polished;Fancy lobster;Stainless Steel;
Polished;Fancy lobster;Stainless Steel;
Polished;Fancy lobster;Stainless Steel;
Polished;Fancy lobster;Stainless Steel;
Polished;Fancy lobster;Stainless Steel;
Polished;Fancy lobster;Stainless Steel;
Polished;Fancy lobster;Stainless Steel;
Polished;Fancy lobster;Stainless Steel;
Polished;Fancy lobster;Stainless Steel;
Polished;Fancy lobster;Stainless Steel;
Polished;Fancy lobster;Stainless Steel;
Polished;Fancy lobster;Stainless Steel;
Polished;Fancy lobster;Stainless Steel;
Polished;Fancy lobster;Stainless Steel;
Polished;Fancy lobster;Stainless Steel;
Polished;Fancy lobster;Stainless Steel;
Polished;Fancy lobster;Stainless Steel;
Polished;Fancy lobster;Stainless Steel;
Polished;Fancy lobster;Stainless Steel;
Polished;Fancy lobster;Stainless Steel;
Polished;Fancy lobster;Stainless Steel;
Polished;Fancy lobster;Stainless Steel;
Polished;Fancy lobster;Stainless Steel;
Polished;Fancy lobster;Stainless Steel;
Polished;Fancy lobster;Stainless Steel;
Polished;Fancy lobster;Stainless Steel;
Polished;Fancy lobster;Stainless Steel;
Polished;Stainless Steel;
Polished;Engravable;Fancy lobster;Stainless Steel;
Polished;Fancy lobster;20" Chain;
Polished;Fancy lobster;Shepherd hook;
Polished;Fancy lobster;Dangle;
Polished;Fancy lobster;Shepherd hook;
Polished;Fancy lobster;Shepherd hook;
Fold-over;CZ;Fancy lobster;Stainless Steel;Brushed;IP black-plated;
Polished;CZ;Stainless Steel;Brushed;IP rose-plated;IP black-plated;Two piece;
Polished;Textured;Stainless Steel;Yellow IP-plated;Set of 3;
Polished;Slip on;Textured;Stainless Steel;Set of 3;
Engravable;Fancy lobster;Stainless Steel;Brushed;Set of two;
Polished;Fancy lobster;Stainless Steel;Set of two;
Polished;Fold-over;Fancy lobster;Stainless Steel;Brushed;Black Carbon Fiber;
Polished;Fancy lobster;Crystal;Stainless Steel;Brushed;Set of two;
Polished;CZ;Fancy lobster;Stainless Steel;Brushed;Set of two;IP black-plated;
Polished;CZ;Fancy lobster;Stainless Steel;Set of two;
Polished;Fold-over;Fancy lobster;Stainless Steel;Black Carbon Fiber;Set of two;
Polished;Fold-over;CZ;Fancy lobster;Stainless Steel;Brushed;Two piece;Yellow IP-plated;
Polished;CZ;Fancy lobster;Stainless Steel;Brushed;Leather cord;Set of two;
Polished;CZ;Fancy lobster;Stainless Steel;Set of two;
Polished;Fancy lobster;Laser-cut;Stainless Steel;
Polished;Fancy lobster;Laser-cut;Stainless Steel;Brushed;
Polished;Enamel;CZ;Stainless Steel;Brushed;
Polished;Enamel;CZ;Stainless Steel;Brushed;Gift Boxed;
Polished;Engravable;Stainless Steel;Gift Boxed;Yellow IP-plated;
;
;
;
;
;
;
;
;
;
;
Polished;14k Yellow gold;Lightweight;
Polished;14K White gold;
Polished;14k Yellow gold;Lightweight;
Polished;14k Yellow gold;
Polished;14k Yellow gold;Lightweight;
Polished;14k Yellow gold;
Polished;14k Yellow gold;Lightweight;
Polished;14k Yellow gold;
Polished;14k Yellow gold;Lightweight;
Polished;14k Yellow gold;
Polished;14k Yellow gold;Lightweight;
Polished;Engravable;Titanium;Half Round;
Polished;Engravable;Titanium;Black Carbon Fiber;
Polished;Engravable;Titanium;Half Round;
Polished;Engravable;Titanium;Half Round;
Polished;Engravable;Titanium;Brushed;Ridged edge;
Polished;Engravable;Titanium;Brushed;Ridged edge;
Polished;Engravable;Titanium;Brushed;Ridged edge;
Polished;Engravable;Titanium;Brushed;Ridged edge;
Polished;Engravable;Titanium;Brushed;Ridged edge;
Polished;Engravable;Titanium;Brushed;Ridged edge;
Polished;Engravable;Titanium;Brushed;Ridged edge;
Polished;Engravable;Titanium;Brushed;Beveled Edge;IP black-plated;
Engravable;Titanium;Brushed;Half Round;
Engravable;Titanium;Brushed;Half Round;
Engravable;Titanium;Brushed;Half Round;
Engravable;Titanium;Brushed;Half Round;
Polished;Engravable;Titanium;Brushed;Beveled Edge;
Polished;Engravable;Titanium;Brushed;Beveled Edge;
Polished;Fold-over;Titanium;Brushed;Yellow IP-plated;
Polished;Engravable;CZ;Titanium;Brushed;
Diamond-cut;Polished;14k Yellow gold;Hollow;Hinged post;
Solid;Polished;14k Yellow gold;Hinged;
Fold-over;White dial;3 atm water resistance;Arabic numerals;Ceramic band;Dial with date;Limited lifetime warranty;Push button deployment;Sapphire crystal;Silver-tone hands;Stainless steel band;Stainless steel case;Stainless steel caseback;Swiss quartz;30mm case;
Fold-over;Black dial;10 atm water resistance;Ceramic band;Dial with date;Limited lifetime warranty;Push button deployment;Roman numerals;Sapphire crystal;Silver-tone hands;Stainless steel band;Stainless steel case;Stainless steel caseback;Swiss quartz;Rotating bezel;31mm case;
Fold-over;White dial;10 atm water resistance;Ceramic band;Dial with date;Limited lifetime warranty;Push button deployment;Roman numerals;Sapphire crystal;Silver-tone hands;Stainless steel band;Stainless steel case;Stainless steel caseback;Swiss quartz;Rotating bezel;31mm case;
Polished;Fold-over;Tungsten;
Solid;Polished;14K White gold;Lobster;Flat;
Solid;Polished;14K White gold;Spring Ring;
Solid;Polished;14K White gold;Spring Ring;
Solid;Polished;14K White gold;Spring Ring;
Solid;Polished;14K White gold;Spring Ring;
Solid;Polished;14K White gold;Spring Ring;
Solid;Polished;14K White gold;Spring Ring;
Solid;Polished;14K White gold;Lobster;
Solid;Polished;14K White gold;Lobster;
Solid;Polished;14K White gold;Lobster;
Solid;Polished;14K White gold;Lobster;
Solid;Polished;14K White gold;Lobster;
Solid;Polished;14K White gold;Lobster;
Solid;Polished;14K White gold;Lobster;
Solid;Polished;14K White gold;Lobster;
Solid;Polished;14K White gold;Lobster;
Solid;Polished;14K White gold;Spring Ring;
Solid;14K White gold;Spring Ring;
Polished;3-D;14k Yellow gold;Hollow;Post;
Polished;3-D;14k Yellow gold;Hollow;Post;
Polished;14k Yellow gold;Hollow;Post;
14k Yellow gold;Post;Freshwater cultured pearl;Round;
Polished;14k Yellow gold;Hollow;Post;
14k Yellow gold;Post;Freshwater cultured pearl;
Polished;3-D;14k Yellow gold;Hollow;Post;
14k Yellow gold;Post;Freshwater cultured pearl;
Polished;14k Yellow gold;Hollow;Post;
Polished;3-D;14k Yellow gold;Hollow;Post;
Polished;3-D;14k Yellow gold;Hollow;
Polished;3-D;14k Yellow gold;Hollow;
Polished;3-D;14k Yellow gold;Hollow;
Polished;3-D;14k Yellow gold;Hollow;
Solid;Polished;14k Yellow gold;Stamped;
Solid;Polished;14k Yellow gold;Stamped;
Solid;Polished;14k Yellow gold;Stamped;
Polished;3-D;14k Yellow gold;Hollow;
14k Yellow gold;Post;Diamond;Saltwater pearl;
14k Yellow gold;Post;Freshwater cultured pearl;Dangle;Pearl clasp;
14k Yellow gold;Post;Diamond;Saltwater pearl;
14k Yellow gold;Post;Diamond;Saltwater pearl;
14k Yellow gold;Post;Spring Ring;Freshwater cultured pearl;
14k Yellow gold;Post;Spring Ring;Freshwater cultured pearl;
14k Yellow gold;Post;Spring Ring;Freshwater cultured pearl;Screw back;
14k Yellow gold;Post;Freshwater cultured pearl;Screw back;
Polished;14k Yellow gold;Post;Freshwater cultured pearl;Fancy lobster;White;
Polished;14k Yellow gold;Post;Freshwater cultured pearl;Fancy lobster;White;
Polished;14k Yellow gold;Post;Freshwater cultured pearl;Fancy lobster;White;
Polished;14k Yellow gold;Post;Freshwater cultured pearl;Fancy lobster;White;
14k Yellow gold;Post;Lobster;Freshwater cultured pearl;Dangle;
14k Yellow gold;Post;Freshwater cultured pearl;Pearl clasp;
14k Yellow gold;Post;Lobster;Freshwater cultured pearl;
14k Yellow gold;Post;Lobster;Freshwater cultured pearl;
14k Yellow gold;Post;Lobster;Freshwater cultured pearl;
Polished;Lobster;Sterling silver;Laser-cut;
Solid;Polished;14k Yellow gold;Open back;Textured;Diamond Cut;
Solid;Polished;Die struck;14k Yellow gold;
Solid;Casted;Polished;14k Yellow gold;Not engraveable by QG;
Solid;Polished;Satin;Die struck;14k Yellow gold;Flat back;Not engraveable by QG;Dangle;
Solid;Die struck;14k Yellow gold;Polished back;Not engraveable;Polished & satin;
Solid;Polished;Satin;Die struck;14k Yellow gold;Flat back;Polished back;Not engraveable by QG;Dangle;
Solid;Polished;Satin;Die struck;14k Yellow gold;Flat back;Not engraveable;
Solid;Polished;Satin;Die struck;14k Yellow gold;Reversible;Not engraveable;Dangle;
Solid;Polished;Satin;Die struck;14k Yellow gold;Flat back;Not engraveable by QG;Dangle;
Solid;Die struck;14k Yellow gold;Polished back;Not engraveable;Polished & satin;
Solid;Die struck;14k Yellow gold;Flat back;Polished back;Not engraveable;Polished & satin;
Casted;Diamond-cut;Polished;14k Yellow gold;Open back;
Engravable;Enamel;Lobster;Sterling silver;
Casted;Polished;Engravable;Enamel;Lobster;Sterling silver;
Casted;Polished;Engravable;Enamel;Lobster;Sterling silver;
Solid;Casted;Polished;Engravable;Enamel;Lobster;Sterling silver;
Casted;Polished;Engravable;Enamel;Lobster;Sterling silver;
Polished;14k Yellow gold;Shell;Cameo;
Polished;14k Yellow gold;Open back;Agate;Oval;Cameo;
Polished;14k Yellow gold;Agate;Oval;Cameo;
Polished;14k Yellow gold;Agate;Oval;Cameo;
Polished;14k Yellow gold;Agate;Cameo;
Polished;14k Yellow gold;Agate;Sentiment on back;Cameo;
Polished;14k Yellow gold;Open back;Shell;Cameo;
Polished;14K White gold;Open back;Freshwater cultured pearl;Shell;Cameo;
Polished;14K White gold;Open back;Freshwater cultured pearl;Shell;Cameo;
Polished;14K White gold;Hollow;Post;
Polished;14K White gold;Hollow;Post;
Polished;3-D;14K White gold;Hollow;Post;
Polished;14K White gold;Hollow;Post;
Polished;14K White gold;Hollow;Post;
Polished;14k Yellow gold;Hollow tube;
Polished;14k Yellow gold;Hollow tube;
Polished;14k Yellow gold;Hollow tube;
Diamond-cut;Polished;Satin;14k Yellow gold;Hollow tube;
Polished;3-D;14k Yellow gold;Hollow;Heart;
Polished;14k Yellow gold;Hollow;
Polished;3-D;14k Yellow gold;Hollow;
Polished;3-D;14k Yellow gold;Hollow;
Solid;Casted;Diamond-cut;Polished;Enamel;14K Yellow gold & rhodium;';

        $str = 'Weight;CT Weight;Gem Weight;Size;Length;Width;Sizeable;Metal Desc;Metal Price;UM Sales;Country Of Origin';
        $attributes = explode(";", $str);
        $attributes = array_map("trim_value", $attributes);
        $attributes =  array_flip($attributes);
$total_createed = 0;
$total_alrady = 0;
        $this->load->model('catalog/attribute');
        
        $sql = "SELECT * FROM " . DB_PREFIX . "attribute_group ag inner JOIN " . DB_PREFIX . "attribute_group_description agd ON (ag.attribute_group_id = agd.attribute_group_id) WHERE agd.language_id = '" . (int)$this->config->get('config_language_id') . "' and agd.name= '$attribute_name'";
       
        
        $query = $this->db->query($sql);
        $result= $query->row;
        
         if($result){
             
         
                
            foreach ($attributes as $attribute=>$value) {

            if($attribute) {
                       
                $filter_data = array(
                'filter_name' => $attribute,
                'filter_attribute_group_id' => $result['attribute_group_id'],
                'start' => 0,
                'limit' => 5
                );

                $results = $this->getAttributes($filter_data);
                if(count($results)) {
                    echo $attribute . ' already exits';
                    $total_alrady++;
                   
                } else {
                    $data['attribute_description'] = array();
                    $data['attribute_description'][(int)$this->config->get('config_language_id')] = array('name' => $attribute);
                    $data['attribute_group_id'] = $result['attribute_group_id'];
                    $data['sort_order'] = '';
                    
                    
                    $this->model_catalog_attribute->addAttribute($data);
                    echo $attribute . ' created';
                    $total_createed++;
                }
                 echo "<br/>";
                 echo "<br/>";
            }
        }
        
        }
        echo $total_createed . ' Attribute Created  in total';
        echo "<br/>";
        echo $total_alrady . ' Attribute Already exists  in total';
        // echo '<pre>';
    }
    
    
    public function getAttributes($data = array()) {
		$sql = "SELECT *, (SELECT agd.name FROM " . DB_PREFIX . "attribute_group_description agd WHERE agd.attribute_group_id = a.attribute_group_id AND agd.language_id = '" . (int)$this->config->get('config_language_id') . "') AS attribute_group FROM " . DB_PREFIX . "attribute a LEFT JOIN " . DB_PREFIX . "attribute_description ad ON (a.attribute_id = ad.attribute_id) WHERE ad.language_id = '" . (int)$this->config->get('config_language_id') . "'";

		if (!empty($data['filter_name'])) {
			$sql .= " AND ad.name = '" . $this->db->escape($data['filter_name']) . "'";
		}

		if (!empty($data['filter_attribute_group_id'])) {
			$sql .= " AND a.attribute_group_id = '" . $this->db->escape($data['filter_attribute_group_id']) . "'";
		}

		$sort_data = array(
			'ad.name',
			'attribute_group',
			'a.sort_order'
		);

		if (isset($data['sort']) && in_array($data['sort'], $sort_data)) {
			$sql .= " ORDER BY " . $data['sort'];
		} else {
			$sql .= " ORDER BY attribute_group, ad.name";
		}

		if (isset($data['order']) && ($data['order'] == 'DESC')) {
			$sql .= " DESC";
		} else {
			$sql .= " ASC";
		}

		if (isset($data['start']) || isset($data['limit'])) {
			if ($data['start'] < 0) {
				$data['start'] = 0;
			}

			if ($data['limit'] < 1) {
				$data['limit'] = 20;
			}

			$sql .= " LIMIT " . (int)$data['start'] . "," . (int)$data['limit'];
		}

		$query = $this->db->query($sql);

		return $query->rows;
	}

}

?>